HabitatMap/AirCastingiOS

AirCasting.xcodeproj/project.pbxproj
AirCasting/Assets.xcassets/aircastingBackground.colorset/Contents.json
AirCasting/ButtonStyles/WhiteButtonStyle.swift
AirCasting/CreateSession/ChooseSessionTypeView.swift
AirCasting/CreateSession/SelectDeviceView.swift
AirCasting/Extensions/Color.swift
AirCasting/Extensions/UIColor.swift
AirCasting/MainTabBarView.swift

**Sidenote**
It's work in progress but I need to switch to connecting with airbeam via BLE to be able to test it on AB3 asap. 
**SUMMARY** 
1. There's a creating session view after selecting "+" tab bar button, where you can select mobile or fixed session.
2. You can see more info spreadsheet, it's not exactly the same as in designs (wip).
3. After selecting mobile session you'll be redirected to the view where you can pick the device. When you click on the button the shadows color should change to blue.

Create session hip

---

AirCasting/CoreData/AirCasting.xcdatamodeld/AirCasting.xcdatamodel/contents
AirCasting/CreateSessionViews/SelectDeviceView.swift
AirCasting/MicrophoneSession/MicrophoneManager.swift
AirCasting/Models/SessionContext.swift
AirCasting/Models/SessionExtension.swift
AirCasting/SessionViews/SessionHeaderView.swift

Data from microphone session gets displayed in dashboard in session cell. It is possible now to stop recording session and it is impossible to start recording another microphone session when the other one is still recording.
* Displaying measurements in sessionHeader
* Add button for stopping microphone session recording
* Prevent creating more than one microphone session

Display microphone session

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/CreateSessionViews/SelectDeviceView.swift
AirCasting/MicrophoneSession/MicrophoneManager.swift
AirCasting/Models/SessionContext.swift
AirCasting/SessionViews/SessionHeaderView.swift
AirCasting/Utils/SettingsManager.swift

* Change flow for checking users permission for microphone. User gets ask to give permission to access microphone when they choose microphone in the `ChooseSessionTypeView`. If they give permission then we go further with the views for creating microphone session. When they don't give permission then they get sent to setting app every time they try to choose microphone
* Add functionality for resuming recording after audio session gets interrupted eg. by incoming phonecall or by another app

Fix microphone session flow

---

AirCasting/APICommunicator/AuthorizationAPI.swift
AirCasting/AuthViews/CreateAccountView.swift
AirCasting/AuthViews/SignInView.swift

Super small fixes: 
1. Changed alerts message when there's an incorrect mail/profile name while creating an account.  
2. Fixed bug - after clicking "continue" in create account view, if the input was wrong the alert was appeared, disappeared by itself, and appeared again. I fixed it by dismissing the keyboard just after clicking the Continue button. Not sure if this "hack" is a solution to this problem but I didn't find anything better.

Quick fixes

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/Graph/Graph.swift
AirCasting/Graph/GraphView.swift
AirCasting/Services/DownloadMeasurmentsService.swift
AirCasting/Services/RemoveOldMeasurementsService.swift

@anna1901 I merged graph part 1 but you asked there why `extension MeasurementStreamEntity {` isn't in a separate file. The answer is: I wanted to have mocked session and mocked stream in one file. If you think I should move it to a separate file, please write a comment in this PR :-) 
**Summary**
- I limit the number of measurements for the fixed session to 1440 (24h of measurements). I create a background context to fetch session, check if any of the session streams has more than 1440 measurements. If yes, I remove the surplus from the beginning of the array of measurements. 
- I add a zoom mobile session graph to show the last 30 minutes by setting 1800 as a maximum visible range for the X axis.

Graph part 2.

---

AirCasting/Settings/SettingsView.swift

https://trello.com/c/zrX0j8UY/126-setting-visually-are-not-presented-as-the-rest-no-padding

UI changed of settings

---

AirCasting/Dashboard/AirSectionPickerView.swift

The bug was: https://trello.com/c/P4N33Xha/75-tabs-for-following-mobile-active-dormant-fixed-in-dashboard
We have a custom section picker and I created a workaround for this, hope it'll work ok. 
I added a ScrollViewReader that scrolls section picker to show the "fixed" tab when the user chooses "dormant", and to show the "following" tab when the user chooses the "active" :)

Add ScrollViewReader

---

AirCasting/MicrophoneSession/MicrophoneManager.swift

This is so bad, but converting dbfs values to db is not possible without at least some calibration (experimented with many other "tricks", but it always boil down to this, so no point in doing any advanced algo here if we don't have this much required anchor)

Naive dBFS -> dB convertion mechanism added

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/AirCastingApp.swift
AirCasting/OfflineMessageViewModel.swift
AirCasting/RootAppView.swift
AirCasting/SessionsSynchronization/Controller/Interfaces/SessionSynchronizerErrorStream.swift
AirCasting/SessionsSynchronization/Controller/SessionSynchronizationController.swift
AirCasting/SessionsSynchronization/Controller/SessionSynchronizer.swift
AirCasting/SessionsSynchronization/Controller/Utils/ScheduledSessionSynchronizerProxy.swift
AirCasting/Utils/OfflineAlert.swift
AirCasting/Utils/Publishers/FilterErrorPublisher.swift
AirCasting/Utils/Publishers/OnErrorPublisher.swift
AirCasting/Utils/Strings.swift
AirCastingTests/ForgotPasswordTests/ForgotPasswordTest.swift
AirCastingTests/Logic/SessionsSynchronization/SynchronizationControllerTestHelpers.swift
AirCastingTests/Logic/SessionsSynchronization/SynchronizationControllerTests.swift
AirCastingTests/Logic/SessionsSynchronization/SynchronizationTestDoubles.swift
AirCastingTests/Other/FilterErrorTests.swift
AirCastingTests/Settings/URLValidationTests.swift

Added an alert that informs the user that synchronization could not be finished if device if offline.
* Added a `SessionSynchronizerErrorStream` as a plugin point for the `SessionSynchronizer`. This way we can redirect the flow of errors completely different way than standard output goes. This allows for a better separation - "normal" views don't need to worry about failure cases, it's handled by separate code in separate place.
* Temporarily commented out tests that were preventing test target to build @jankrzempek please take care of this

No connection alert for sync

---

AirCasting/SessionViews/SessionHeaderView.swift
AirCasting/Utils/Strings.swift

What was done:
Resume button from action menu was deleted
https://trello.com/c/wse6KjVB/185-mobile-active-mobile-dormant-fixed-card-menu-button-remove-resume-recording

removed resume button

---

AirCasting/APICommunicator/AuthorizationAPI.swift
AirCasting/Settings/BackendSettingsView.swift
AirCasting/Settings/SettingsView.swift
AirCasting/URLProviders/BaseURLProvider.swift
AirCasting/Utils/Strings.swift

What was done:
Now there is only one url and if it changes then the whole app, including signing in depends on it.
Done things from the checkboxes from the ticket.
https://trello.com/c/kAzjpy2N/117-settings-backend-url

Changing backend settings - additional changes

---

AirCasting/SessionViews/SessionCartView.swift

What was done:
Map button was changed to if {} and now only shown when not indoor && fixed
https://trello.com/c/Ky1FINec/154-indoor-sessions

fixed session indoor - map button removed

---

AirCasting/CreateSessionViews/CreateSessionDetailsView.swift
AirCasting/MicrophoneSession/MicrophoneManager.swift
AirCastingTests/API/SyncDownstreamServiceTests.swift

Baselining so that sessions uploaded from the iOS application are visible on the web app:
* indoor flag fixed for mobile sessions (@smialko please confirm this is correct)
* device name for microphone changed from `Phone Microphone-dB` to `Phone Microphone` to match Android
Note that for this PR to take effect we'll need to also have #135 and #136

Session uploads and data baselined with android platform

---

AirCasting/Models/AirBeamFixedSessionCreator.swift

What was done:
Contribute is now passed based on the user settings
IsIndoor is now passed based on the user settings
Ensured that enditme changes and location is provided
Notes are not implemented yet
https://trello.com/c/CKQvtcXH/173-create-session-check-if-contribute-isindoor-location-endtime-are-not-mocked

Changed mocked data

---

AirCasting/CreateSessionViews/Handlers/BluetoothHandler.swift
AirCasting/CreateSessionViews/SelectDeviceView.swift

There were two bugs:
One of them was with mobile bluetooth session -> bluetooth popup has not appeared before going to searching devices -- Done
Second was with microphone session -> When you have proceed and then try to go back, app crashed (there was unused line of code) -- Done

Microphone and bluetooth bug

---

AirCasting/ABConnector/BluetoothManager.swift
AirCasting/CreateSessionViews/Handlers/BluetoothHandler.swift
AirCasting/CreateSessionViews/SelectDeviceView.swift
AirCasting/CreateSessionViews/TurnOnBluetoothView.swift
AirCasting/RootAppView.swift
AirCasting/URLProviders/UserDefaultsBaseURLProvider.swift
AirCasting/Utils/SystemSettings.swift

Bug: There's no "Turn on Bluetooth" view even if the Bluetooth was powered off. The app allowed me to go to select device view and it was "searching" for devices even though Bluetooth was off.
I had to remove Dependencies and refactored RootAppView.swift. It wasn't the first time it caused hard-to-find bugs, so I decided to fix it for the future. And it was one of the reasons why the TurnOnBluetoothView was displayed when Bluetooth was on and authorized. :)

Fix bluetooth bug

---

AirCasting/SessionViews/SessionCartView.swift

In addition to this: https://github.com/HabitatMap/AirCastingiOS/pull/157 
After those two tickets isIndoor will be handled in every case, so that in this ticket we are able to shorten IF
https://trello.com/c/jp738Egu/221-fixed-outdoor-dashboard-map-button-is-missing

Map button - outdoor

---

AirCasting/CoreData/PersistenceController+Database.swift
AirCasting/Services/DownloadMeasurmentsService.swift

What was done is well explained here: https://trello.com/c/th6aThho/71-replace-mocked-lastsync-date-in-updateforsession-funcion-in-downloadmeasurementsservice

Fixed measurements are fetched by lastSync date

---

AirCasting/CreateSessionViews/CreateSessionDetailsView.swift

https://trello.com/c/ZRoqJXu3/244-fixed-wizard-move-wifi-to-the-left-make-it-the-default-selection
What was done:
Although the wifi is picked now as the default we are somehow ensure that user type the password because the wifi warning popup will appear 
Changes Wifi and cellular

wifi to the left

---

AirCasting/Info.plist
AirCasting/Models/AirBeamFixedSessionCreator.swift

Can't test it well because it was working properly on my phone before those changes, but app should be able to communicate with AB3 (mobile active sessions) in background.

Add bluetooth-central Background Execution Mode

---

AirCasting/AuthViews/UserSettings.swift
AirCasting/CreateSessionViews/CreateSessionDetailsView.swift
AirCasting/CreateSessionViews/PlacePicker.swift
AirCasting/Map/GoogleMapView.swift
AirCasting/Map/LocationTracker.swift
AirCasting/Map/PathPoint.swift
AirCasting/Settings/SettingsView.swift

What was done:
https://trello.com/c/XkbtqPbo/116-settings-contribute-to-crowd-map
Now the default state of the toggle is "ON"
UI - text is now well laid
Ensured that contriuteToCrowdMap changes all the time and the proper state is sent during the session creation process

ContributToCrowdMap fix 

---

AirCasting/SessionViews/SessionCartView.swift

What was changed for fixed sessions: 
when followed the card should show values when collapsed and chart & buttons when expanded. 
when unfollowed the card should show only show stream names and when expanded values & buttons.

Change views for fixed followed &unfollowed

---

AirCasting/SessionViews/SingleMeasurementView.swift

It comes out that one line will do the job (Heh) 
https://trello.com/c/kUfhVyt0/236-all-tabs-double-digit-measurements-break-the-formatting

formatting measurements text

---

AirCasting/Map/GoogleMapView.swift
AirCasting/Utils/Constants.swift

Michael asked to make the polyline thinner & and a dot at the end of the polyline. I decided to use GMSMarker instead of GMSCircle because GMSCircle doesn't change its width when scaling the map so it's invisible after zoom out.
Task: https://trello.com/c/jv3Hk6EG/227-mobile-map-improve-mapping-visualization

Add dot to mobile session's map

---

AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift

https://trello.com/c/4jwm8TYp/301-accessing-wizard-with-dashboard-button-record-mobile-session-results-in-blank-confirmation-view

handle no crashing when making dashboard session

---

AirCasting/CoreData/MeasurementStreamStorage.swift
AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
AirCasting/CreateSessionViews/CreateSessionDetailsView.swift
AirCasting/MicrophoneSession/MicrophoneManager.swift
AirCasting/MobilePeripheralSessionManager.swift
AirCasting/Models/AirBeamCellularSessionCreator.swift
AirCasting/Models/AirBeamFixedWifiSessionCreator.swift
AirCasting/Models/SessionCreator.swift
AirCasting/SessionStopping/MicrophoneSessionStopper.swift
AirCasting/SessionViews/SessionCartFollowing.swift
AirCasting/SessionViews/SessionCartViewModel/DefaultSyncingMeasurementsViewModel.swift
AirCastingTests/Logic/SessionsSynchronization/SynchronizationTestMocks.swift

Long story short I added an `accessStorage` which ensures thread-safety by dispatching all calls to the queue owned by the NSManagedObjectContext. This way app won't crash on creating a mobile AB session, the graph is being drawn, measurement can be synced, etc.

Refactor to fix app crashing after creating ABmobile session & syncing measurments

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/AirCastingApp.swift
AirCasting/CoreData/PersistenceController+Database.swift
AirCasting/CoreData/PersistenceController.swift
FixedSessionFaker.swift

Core data stack changed to a parent/child model with a `single source of truth` pattern:
1. Only one, "main" `NSManagedObjectContext` is responsible for writing to the store (and it's a background one)
2. The UI Context as well as edit contexts are children of the main context
3. Changes from the main context to the UI context are being propagated only when the new `uiSuspended` flag is not set
* `FixedSessionFaker` left in the code - it might be handy (it's faking a running fixed session with random measurements)

Added ability to cut out UI updates from storage (Core Data stack)

---

AirCasting/MainTabBarView.swift

Now when you enter the HeatMap setting from Graph or a Map it immediately goes back - it shouldn't now

making heatmap settings not to go back

---

AirCasting/Map/AirMapView.swift

When user leaves the app while in map view it will pop to prevent major CPU usage and app kill. **This is a bandaid solution**

Popping navigation stack when in mapview and going background

---

AirCasting/SessionViews/SingleMeasurementView.swift

Removing the padding on text in singleMeasurementView fixes an issue with measurement values and dots not being aligned with the name.

Remove padding to center measurements names with dots and values

---

AirCasting/SessionViews/ABMeasurementsView.swift
AirCasting/SessionViews/SingleMeasurementView.swift

I'm not sure how it worked previously. Right now we're observing stream on SingleMeasurementView and get value from this observed stream :)

Make stream ObservedObject on SingleMeasurementView

---

AirCasting/CoreData/MeasurementStreamStorage.swift
AirCasting/MicrophoneSession/MicrophoneManager.swift
AirCasting/MobilePeripheralSessionManager.swift
AirCasting/SessionViews/ABMeasurementsView.swift
AirCasting/SessionViews/SessionCartViewModel/DefaultSyncingMeasurementsViewModel.swift
AirCasting/SessionViews/SingleMeasurementView.swift

Tbh I thought this will be just a first step of fixing the 0-values on dormant sessions but it wasn't. Also, removing save from `addMeasurementValues` improved the performance of saving measurements.

Syncing measurements for dormant sessions - fixes

---

AirCasting/Extensions/Date+Miliseconds.swift
AirCasting/SessionViews/ChartEntriesCreator.swift

Rounding beginning and end of each time interval seems to fix the problem with "dancing chart" (varying number of measurements included in the time interval).

Round time interval to seconds to fix the chart

---

AirCasting.xcodeproj/project.pbxproj
AirCasting.xcworkspace/xcshareddata/swiftpm/Package.resolved
AirCasting/AirCastingApp.swift
AirCasting/CoreData/AirCasting.xcdatamodeld/AirCasting.xcdatamodel/contents
AirCasting/CoreData/MeasurementEntity.swift
AirCasting/CoreData/MeasurementStreamStorage.swift
AirCasting/CoreData/PersistenceController.swift
AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
AirCasting/Dashboard/DashboardView.swift
AirCasting/Utils/AveragingService.swift

1. Added observer to the database which checks if there's a mobile recording session
2. After the session is added/"removed" this method is automatically called` func controller(_ controller: NSFetchedResultsController<NSFetchRequestResult>, didChange anObject: Any, at indexPath: IndexPath?, for type: NSFetchedResultsChangeType, newIndexPath: IndexPath?)` and either start the timer for this session or stops it
3. There's a timer that after 2 hours of recording calls a method that perform averaging every 5s
4. Averaging method wasn't built by me, I just refactored it a bit :)

Mobile sessions averaging [WIP]

---

AirCasting/SessionViews/ChartViewModel.swift
AirCasting/SessionViews/SessionCartView.swift

This PR fixes issue with:
- chart not appearing for followed session (only for the first followed session) until the stream was selected
- chart not refreshing for mobile AB sessions

Start timers for chart for new sessions and refresh chart on appear

---

AirCasting/Dashboard/AirSectionPickerView.swift
AirCasting/Dashboard/DashboardView.swift

https://trello.com/c/4RrL5LWV/333-dashboard-all-tabs-reduce-vertical-space-between-cards-so-it-matches-the-android-app
The main idea for this is to reduce the size between picker buttons and match the app closer to android

reduce the size between sections

---

AirCasting/SessionViews/SessionHeaderView.swift

https://trello.com/c/QCLBjaqV/355-dashboard-session-titles-remove-additional-bolding

change title to regular to match android

---

AirCasting/Graph/StatisticsContainer/Adapters/MapStatsDataSource.swift
AirCasting/Map/AirMapView.swift
AirCasting/Map/GoogleMapView.swift
AirCasting/SessionViews/SessionCartView.swift

This removes (or actually comments out, cause it might be useful in the future) functionality for showing statistics in zoomed area on map only. Instead we are always showing statistics for all of the measurements for selected stream

Stats container fix

---

AirCasting/Dashboard/DashboardView.swift

Fix log out crash by filtering out sessions with empty uuid. This is probably a temporary solution.

Fix log out crash

---

AirCasting/Extensions/SensorThreshold.swift

https://trello.com/c/Zs7NWpAs/374-mobile-active-following-stats-container-threshold-values-should-be-colored-according-to-the-hlu

added closed range to the last color

---

AirCasting/CreateSessionViews/ChooseCustomLocationView.swift
AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
AirCasting/Map/AirMapView.swift
AirCasting/Map/GoogleMapView.swift

https://trello.com/c/31DSosIn/397-mobile-active-map-stay-on-map
I know that this code implemented with .scenePhase was there for a reason, but do we really need it still? We have UI suspending feature that works as user locks the phone or put app in the background. I've made other solution to specifically prevent GoogleMap updates instead of going back to homescreen, but do we really need it now?

stay on map

---

AirCasting/ABConnector/BluetoothManager.swift

This fixes the leftover bug and prevents the app from reconnecting with the AirBeam when it was set to a fixed session and not active mobile session.

Reconnect only for mobile active session peripheral

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/MicrophoneSession/AVSessionInterruptionHandler.swift
AirCasting/MicrophoneSession/MicrophoneManager.swift

[Trello](https://trello.com/c/7M33g3AR/334-microphone-doesnt-resume-recording-when-other-app-was-using-a-microphone-and-then-we-came-back-to-the-app)
* `.duckOthers` option added to our audio session. This means any other AV session will be blocked by us (for example Music app won't be able to play music because of us).
* Moved `AVAudioRecorder` to a single-instance per `MicrophoneManager` instance. This is because it's not possible to create new recorders while in background. We need one and pause/resume it instead.
* Proper session activation/deactivation mechanism added with error handling (TODO)
* `AVSessionInterruptionObserver` implemented in place of the deprecated delegate we've been using.

Background audio interruptions problems fixed

---

AirCasting/ABConnector/AirBeamServices.swift
AirCasting/ABConnector/BluetoothManager.swift
AirCasting/Utils/AirCastingNotifications.swift

* When reconnecting with device previously we were waiting 4 seconds before sending configuration. Now we are waiting for the discovered characteristic notification
* In the notification I added user info with a peripheral uuid just to double check that discovered characteristic notification is related to the right peripheral

Wait for discovered characteristics when reconnecting with ab

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/CoreData/MeasurementStreamEntity.swift
AirCasting/CoreData/PersistenceController.swift
AirCasting/Graph/Graph.swift
AirCasting/Graph/GraphView.swift
AirCasting/Map/AirMapView.swift
AirCasting/SessionViews/ThresholdSettings/ThresholdsSettingsView.swift
AirCasting/SessionViews/ThresholdSettings/ThresholdsSettingsViewModel.swift

I renamed HeatmapSettingsView because I think this name would be confusing after implementing heatmap.

Reset thresholds to default

---

AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsView.swift
AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsViewModel.swift
AirCasting/Utils/Strings.swift

https://trello.com/c/MQepK0pv/431-config-wizard-fixed-wifi-text-updates

format fonts and colors - WiFi Wizard

---

AirCasting/Settings/BackendSettingsView.swift

It appeared we had a bad endpoint (I mean not complete). When using some custom one we were missing /api. I've added it like that not to mess up anything else in the app and I think it is ok. 
Tested and working as expected :)

fix endpoint - Backend URL

---

AirCasting/Map/GoogleMapView.swift
AirCasting/Map/LocationTracker.swift

https://trello.com/c/8ds8HKNv/445-103-config-wizard-fixed-outdoor-session-is-not-geolocated-accurately

fix geolocation - are you ready

---

AirCasting/Info.plist
AirCasting/Map/LocationTracker.swift

https://trello.com/c/I2lEvikR/435-mobile-active-app-loses-gps-fix-when-in-background

app loses GPS - background

---

AirCasting/FeatureFlags/FeatureFlagProviders/OverridingFeatureFlagProvider.swift
AirCasting/FeatureFlags/FeatureFlagsViewModel.swift

After updating from beta/development builds to release the feature flag overrides were still in place and couldn't be switched without app reinstall

Release flags override fix

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/AuthViews/UserSettings.swift
AirCasting/Extensions/UserDefaults.swift
AirCasting/Utils/Constants.swift

This just adds a small fix to UserSettings. Previously we were always setting contributingToCrowdMap to true at the app launch and now we will take them from userdefautls

Get settings for crowd map from user defaults at the start of the app

---

AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsView.swift
AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsViewModel.swift

Show error only when (from Michael):
. show this message only if: the session name field is blank AND the user taps "Continue".

Session name empty - error

---

AirCasting/AuthViews/UserSettings.swift
AirCasting/FeatureFlags/FeatureFlagProvider.swift
AirCasting/FeatureFlags/FeatureFlagProviders/DefaultFeatureFlagProvider.swift
AirCasting/FeatureFlags/FeatureFlagProviders/FirebaseFeatureFlagProvider.swift
AirCasting/Settings/SettingsView.swift

It's much easier to read when a feture always *turns something on*, not off.
Kudos to @anna1901 for a great name suggestion 🚀

Change locationless feature flag name: .disableMapping -> locationlessSessions

---

AirCasting/SessionsSynchronization/Controller/Utils/SessionsSynchronizationStoreDataConverter.swift
AirCasting/SingleSessionSynchronizer/SessionUpdateService.swift

https://trello.com/c/qUetu2QY/513-sort-notes-before-sending-to-web
Notes need to be sorted, before being uploaded on the web. It results in placing them in the right order.

Sort notes before uploding to web.

---

AirCasting/Map/AirMapView.swift

For now, graph was able to push everything to the top, when there was no measurements. The map was not able to do it, now it matches the grpah convention and it can.
https://trello.com/c/Jzmj9B7B/497-fix-ui-alignment-airbeam-session

Alligning graph and map the same way.

---

AirCasting/CoreData/NSManagedObjectContext+Utils.swift
AirCasting/CoreData/PersistenceController+Database.swift
AirCasting/CoreData/Session.swift
AirCasting/Models/AirBeamCellularSessionCreator.swift
AirCasting/Models/AirBeamFixedWifiSessionCreator.swift
AirCasting/SessionsSynchronization/Adapters/DataStore/SessionSynchronizationDatabase.swift
AirCasting/SessionsSynchronization/Adapters/Services/SessionUploadService.swift
AirCasting/SessionsSynchronization/Controller/Interfaces/SessionSynchronizationStore.swift
AirCasting/SessionsSynchronization/Controller/Interfaces/SessionUpstream.swift
AirCasting/SessionsSynchronization/Controller/SessionSynchronizationController.swift
AirCastingTests/API/SyncContextServiceTests.swift
AirCastingTests/API/SyncDownstreamServiceTests.swift
AirCastingTests/API/SyncUpstreamServiceTests.swift
AirCastingTests/ForgotPasswordTests/ForgotPasswordTest.swift
AirCastingTests/Logic/SessionsSynchronization/SynchronizationControllerTestHelpers.swift
AirCastingTests/Logic/SessionsSynchronization/SynchronizationControllerTests.swift
AirCastingTests/Logic/SessionsSynchronization/SynchronizationTestDoubles.swift
AirCastingTests/Logic/SessionsSynchronization/SynchronizationTestMocks.swift

URLs received as a server response for uploaded sessions are now properly saved in the database
Trello: https://trello.com/c/3ti2pNwF

Save session url on upload

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/CreateSessionViews/ABConnectedView.swift
AirCasting/CreateSessionViews/ChooseCustomLocationView.swift
AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeViewModel.swift
AirCasting/CreateSessionViews/ConnectingABView.swift
AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsView.swift
AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsViewModel.swift
AirCasting/CreateSessionViews/PowerABView.swift
AirCasting/CreateSessionViews/SelectDeviceView.swift
AirCasting/CreateSessionViews/SelectPeripheralView.swift
AirCasting/CreateSessionViews/TurnOnBluetoothView.swift
AirCasting/CreateSessionViews/TurnOnLocation/TurnOnLocationView.swift
AirCasting/CreateSessionViews/TurnOnLocation/TurnOnLocationViewModel.swift
AirCasting/CreateSessionViews/TurnOnLocationFixed/TurnOnLocationFixedView.swift
AirCasting/CreateSessionViews/TurnOnLocationFixed/TurnOnLocationFixedViewModel.swift
AirCasting/SDSync/ViewsFlow/BackendSyncCompleted/BackendSyncCompletedView.swift
AirCasting/SDSync/ViewsFlow/SDRestartAB/SDRestartABView.swift
AirCasting/Settings/SettingsView.swift

The location screen which prompts the user to give the app access to the Location was moved to 'after SessionDetailsView' in the case when session is fixed. On the mobile it stays as it is.
https://trello.com/c/M3fRJ3wn/500-allow-users-to-create-fixed-session-even-if-they-have-location-tracking-disabled-but-keep-the-turn-on-location-view-as-a-reminde

Location screen for fixed session moved.

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/CreateSessionViews/TurnOnLocation/TurnOnLocationView.swift
AirCasting/CreateSessionViews/TurnOnLocationFixed/TurnOnLocationFixedView.swift
AirCasting/CreateSessionViews/TurnOnLocationFixed/TurnOnLocationFixedViewModel.swift
AirCasting/Extensions/ViewControl.swift

Discussed on the call:
Now when session if fixed and indoor the location screen is skipped. When session is fixed and outdoor, the location screen is shown as a reminder and an option for the user. The only requirement is to allow location when doing mobile session without disabled mapping. In this commit, we are handling a special case where users could have location services turned off at all and never get an Apple popup about location.
https://trello.com/c/M7Jk012v/529-mobile-fixed-wizard-location-services-off-cant-continue-through-wizard

Logic for requesting location changed.

---

AirCasting/ABConnector/SDSyncController.swift
AirCasting/SDSync/FixedSessions/SDCardFixedSessionsSavingService.swift

I found and solve a small bug. The sd sync wasn't completing when there were no fixed sessions to be uploaded,

Return completion success when there are no fixed sessions to upload

---

AirCasting/CoreData/MeasurementStreamStorage.swift
AirCasting/Models/SessionExtension.swift
AirCasting/Services/DownloadMeasurmentsService.swift
AirCasting/SessionViews/ABMeasurementsView.swift
AirCasting/SessionViews/SessionCardView.swift
AirCasting/SessionViews/SessionCartViewModel/DefaultSyncingMeasurementsViewModel.swift
AirCasting/SessionsSynchronization/Adapters/Services/SessionDownloadService.swift

I think it will improve performance a lot. Currently we are downloading measurements for all of the fixed sessions and for each of those sessions we are triggering call to api and then updating session params in core data. I think it is probably not necessary to do it for sessions which are not followed.
* limit periodic measurements download to followed sessions only
* download new measurements for followed sessions on card expand
* remove saving cardToggle state for fixed not followed sessions
Additional improvements:
* remove 2 seconds wait before calling completion in session downloader (it was causing the long waiting for measurements download and I think most likely it was not necessary - should be tested to check if it didn't break anything important)

Get only followed sessions in DownloadMeasurementsService

---

AirCasting/CoreData/MeasurementStreamStorage.swift
AirCasting/Map/GoogleMapView.swift
AirCasting/Notes/NotesHandler.swift
AirCasting/SessionViews/SessionCartViewModel/DefaultDeleteSessionViewModel.swift
AirCasting/SingleSessionSynchronizer/SessionUpdateService.swift

This was broken by changes to updateSession implementation and it wasn't working if sessions wasn't present on backend. Now it is fixed.

Fix deleting and editing notes and deleting streams

---

AirCasting/SessionsSynchronization/Adapters/Services/SessionDownloadService.swift

The URL was changed in [previous PR](https://github.com/HabitatMap/AirCastingiOS/commit/b7e52c40e30fcff032cd99a0aa044108108e017d#commitcomment-70392380) and it was probably by mistake, so we are changing it back.

Revert change of url used for downloading sessions during sync

---

AirCasting/ABConnector/HexMessagesBuilder.swift

Now, whenever you do have some kind of "Ś" or "Ę" in you wifi password or SSID the app will crash. The reason is that ASCII is not able to convert those characters. 
The purpose of this PR is to allow UTF8 converting when ASCII cannot. We want to stay with ASCII as it was working well most of the time. The second reason is UTF8 and ASCII is not the same all the time and Raymond advice not to use UTF8 for everything. 
I think that this is the safest approach for now and it does work as it should. My SSID has "Ś" and with this code everything goes well.
https://trello.com/c/8EDmXgpc/580-specials-characters-are-not-converted-to-ascii
https://trello.com/c/FNZjsdkv/610-hexmessagebuilder

Utf8 as an additional way of convertion.

---

AirCasting/AirCastingApp.swift
AirCasting/MobilePeripheralSessionManager.swift

Protect screen shows only when mobile session is on.
https://trello.com/c/UuRsghpc/607-consider-custom-app-switcher-screen-to-ensure-that-app-wont-be-terminated-during-recording-a-session -- comment

Protect screen - only mobile.

---

AirCasting/CreateSessionViews/PlacePicker/PlacePicker.swift
AirCasting/SearchAndFollow/SearchLocation/SearchPickerService.swift

https://trello.com/c/4l288e33/634-sf-search-fixed-sessions-after-entering-an-address-that-includes-a-street-the-city-is-not-included-in-the-address-bar

Show full adress in the textField

---

AirCasting/APICommunicator/SingleSessionDownloader.swift

It's just a small fix. The endpoint was originally copied from the sessionsDownloader user for sync when that endpoint was wrong.

Change the url to empty.json

---

AirCasting/SearchAndFollow/SearchAndFollowMap/MapSessionMarker.swift
AirCasting/SearchAndFollow/SearchAndFollowMap/SearchAndFollowMap.swift
AirCasting/SearchAndFollow/SearchMap/SearchMapView.swift
AirCasting/SearchAndFollow/SearchMap/SearchMapViewModel.swift

Execute code only when needed, after map idle is detected. Deleted what was not needed for map and search reload implementation - dismissView function for modal sheet.
+ The code for reloading dots on the map and refreshing the views was executing many times, now it should be improved.
https://trello.com/c/czdkWCr0/642-sf-map-after-entering-new-location-map-pans-to-new-location-but-results-arent-updated

Fix location reload on S&F feature

---

AirCasting/APICommunicator/FixedSession.swift
AirCasting/SDSync/FixedSessions/SyncedMeasurementsDownloadingService.swift

https://trello.com/c/BoXuTSwl/651-170-2-following-card-timestamps-charts-not-refreshing-on-view-nor-on-pull-down
https://trello.com/c/YyY6cgEL/652-170-2-fixed-card-timestamps-lmms-not-updating-on-expand

Fix autoupdating data for followed sessions

---

AirCasting/Extensions/ViewControl.swift
AirCasting/SessionViews/ThresholdSettings/ThresholdsSettingsView.swift
AirCasting/Utils/Strings.swift

https://trello.com/c/4qBI79YP/650-changing-keyboard-type-in-thresholds-settings-view
Two ways of handling the keyboard because the toolbar for the keyboard is available only for iOS 15.0 and higher. So for iOS > 15 users will tap "Done" to dismiss the keyboard as per the attached screenshot. Whereas for iOS versions lower than 15 the user will tap anywhere to dismiss the keyboard.

Changing keyboard type in ThresholdsSettingsView

---

AirCasting/SessionViews/ThresholdSettings/ThresholdsSettingsView.swift

https://trello.com/c/XHxEV3u5/658-1702-heatmap-settings-after-entering-a-new-threshold-value-and-tapping-done-the-updated-value-returns-to-its-prior-value
A problem occurred only on smaller devices, so please test on Iphone8/SE/Mini.

Fixing problem with dismissing keyboard

---

AirCasting/Map/AirMapView.swift

https://trello.com/c/hlMFnv9k/668-the-statistic-container-has-no-initial-values-on-the-map

The statistic container without initial values

---

AirCasting/Dashboard/EmptyDashboardButtonView.swift

https://trello.com/c/jglC0rdf/691-fixing-bug-when-clicking-record-new-session

Fixing bug which shows inappropriate view after clicking Record New Session

---

AirCasting/Models/AirBeamCellularSessionCreator.swift

There was a small bug for creating indoor cellular sessions. We were not passing this argument when creating a session struct and it was set to false by default. This PR fixes that.

Fix adding indoor argument when creating cellular sessions

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/CreateSessionViews/SelectPeripheralView.swift
AirCasting/CreateSessionViews/TurnOnBluetoothView.swift
AirCasting/SDSync/ViewsFlow/BackendSyncCompleted/BackendSyncCompletedView.swift
AirCasting/SDSync/ViewsFlow/SDRestartAB/SDRestartABView.swift
AirCasting/SDSync/ViewsFlow/SDSyncComplete/SDSyncCompleteView.swift
AirCasting/SDSync/ViewsFlow/SDSyncRootView/SDSyncRootView.swift
AirCasting/SDSync/ViewsFlow/SDSyncUnplugAB/UnplugABView.swift
AirCasting/SDSync/ViewsFlow/SDSyncingAB/SyncingABView.swift

Progress View inside the AB sync flows equally divided to look well visually.
**Where:**
This PR only covers the ProgressBar inside the `Sync data from AB`.
**What:**
ProgressBar is divided into 7 parts. The value corresponding to each screen was assigned to it.
https://trello.com/c/CJ4oNJ95/728-improved-progressbar-sync-data-from-ab

Progress View improved - SD Sync flow

---

AirCasting/Onboarding/GetStarted.swift

https://trello.com/c/947D1T0q/740-intro-wizard-1st-screen-bold-button-text-reading-get-started-make-button-border-darker

Bolder text and bolder line - GetStarted screen.

---

AirCasting/AuthViews/UserSettings.swift
AirCasting/Dashboard/Reordering/ReorderingSessionHeader.swift
AirCasting/Graph/GraphRenderers.swift
AirCasting/SearchAndFollow/CompleteScreen/Views/CompleteScreen.swift
AirCasting/SearchAndFollow/CompleteScreen/Views/Header/StaticSessionHeader.swift
AirCasting/SearchAndFollow/SearchMap/BottomCardViewModel.swift
AirCasting/SessionViews/ChartView.swift
AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionHeader.swift
AirCasting/SessionViews/SessionHeaderView.swift
AirCasting/Settings/SettingsView.swift
AirCasting/Utils/Constants.swift
AirCasting/Utils/DataFormatters.swift
AirCasting/Utils/Strings.swift

Applied 12h format to DateFormatters which we currently use. After that conditionally decide which one is proper at the given moment. The default state for this setting ON after installation.
https://trello.com/c/PcNTJiAE/734-settings-use-24-hour-format-toggled-on-by-default

Setting section which allows to switch between 12/24 hour format.

---

AirCasting/SearchAndFollow/SearchLocation/SearchView.swift

When you tap on the explore session button and then go to `create session` screen - S&F screen will always appear.
https://trello.com/c/syJ6K83c/739-navigates-to-sf

Explore sessions button - fix

---

AirCasting.xcodeproj/project.pbxproj
AirCasting.xcodeproj/xcshareddata/xcschemes/AirCasting.xcscheme
AirCastingUITests/AirCastingUITestsLaunchTests.swift
AirCastingUITests/ExploreSessionButtonTests.swift

Covered explore session button flow in which SF screen could appear always on + button click.
To check please move `exploreSessionsButton.exploreSessionsButtonTapped = false` to viewInitialized.

ExploreSession button bug - UITests

---

AirCasting/SessionViews/EditViewModel.swift
AirCasting/SessionViews/SessionHeaderView.swift

Before, user couldn't edit a session if it wasn't previously sent to backend. It was happening because when entering session editing view we were attempting to get its most recent data from backend and it was failing because session wasn't there. Now, we will allow users to edit sessions that weren't sent to backend (because eg. user has "sync only through wifi" turned on).

Allow for editing not synced sessions

---

AirCasting/SessionViews/EditViewModel.swift
AirCasting/Utils/InAppAlerts.swift
AirCasting/Utils/Strings.swift

This PR adds a network check to the edit view and show the right alert when a user tries to edit a session but they don't have an internet connection.

Check for internet connection and show the right alert in edit view

---

AirCasting/CoreData/Storages/MeasurementStreamStorage.swift
AirCasting/CoreData/Storages/UIStorage.swift
AirCasting/MicrophoneSession/LevelMeasurementController/DecibelMeasurementSaveable.swift
AirCasting/MobilePeripheralSessionManager.swift

**What was done:**
The initial state of the card should be set to _expanded_ when doing a mobile session (BT or MIC)
https://trello.com/c/4zpZcHT1/784-mobile-active-make-expanded-card-the-default-state

Expand card when doing a mobile session.

---

AirCasting/ABConnector/BluetoothManager.swift
AirCasting/MobilePeripheralSessionManager.swift

We were having different timestamps assigned to one chunk (5 of them: F, PM1..) of measurements. The reason is that: we were saving each one of them separately which sometimes resulted in a slight delay.
It should be tested for +2 h and +9 hours sessions, but I think Michael and Grzester can do it later, as for now, those early tests done by me were successful.
https://trello.com/c/Y4OVpvQH/347-improve-2hr-9hr-averaging-function-so-all-the-averages-are-precisely-5-sec-1-min

Assign the same timestamp to given measurements chunk.

---

AirCasting/Notes/AddNote/AddNoteView.swift
AirCasting/Notes/AddNote/AddNoteViewModel.swift
AirCasting/Notes/EditNote/EditNoteView.swift
AirCasting/Notes/EditNote/EditNoteViewModel.swift
AirCasting/Utils/Strings.swift

When we are sending a note without a text backend sends 400 response and session can't be synced.
https://trello.com/c/rGlWKHMU

Add validation for note text

---

AirCasting/CoreData/PersistenceController+Database.swift
AirCasting/SessionsSynchronization/Adapters/DataStore/SessionSynchronizationDatabase.swift
AirCasting/SessionsSynchronization/Adapters/Services/SessionDownloadService.swift
AirCasting/SessionsSynchronization/Controller/Interfaces/SessionDownstream.swift
AirCasting/SessionsSynchronization/Controller/Interfaces/SessionSynchronizationStore.swift
AirCasting/SessionsSynchronization/Controller/Utils/SessionsSynchronizationStoreDataConverter.swift

This PR adds a part of adding photos to notes that was missing, which is saving photo url after we receive session data when downloading it during sync with backed.
Before, when user signed out and signed backed in to the app, notes photos were not appearing. Now they are.
https://trello.com/c/hYCtbmeL

Save photo url after downloading session from backed

---

AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift

**Goal:**
- make smaller spaces between buttons to fit `mobile sessions` in one line and `Sync data from AB3` in two lines
- improve the design so that, when one icon will be missing - it will still look good (iPhone SE case)
- when only one icon appear on the bottom, move it to the left side

Proper size of + screen buttons.

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/CoreData/AirCasting.xcdatamodeld/.xccurrentversion
AirCasting/CoreData/AirCasting.xcdatamodeld/AirCasting v9.xcdatamodel/contents
AirCasting/CoreData/MeasurementEntity.swift
AirCasting/CoreData/NSManagedObjectContext+Utils.swift
AirCasting/CoreData/PersistenceController+Database.swift
AirCasting/Models/Session+Mock.swift
AirCasting/Services/UpdateSessionParams.swift
AirCasting/SessionsSynchronization/Adapters/DataStore/SessionSynchronizationDatabase.swift
AirCasting/SessionsSynchronization/Controller/Interfaces/SessionSynchronizationStore.swift
AirCasting/SessionsSynchronization/Controller/Utils/SessionsSynchronizationStoreDataConverter.swift
AirCasting/SessionsSynchronization/Database/DatabaseMeasurement.swift
AirCastingTests/Logic/SessionsSynchronization/SynchronizationTestMocks.swift
AirCastingTests/Logic/Statistics/TestStreamGenerator.swift
AirCastingTests/Model/UpdateSessionParamsServiceTests.swift
FixedSessionFaker.swift

MeasurementEntity had an `id` attribute, which was never used for anything, so it gets deleted.

Remove id from measurement entity

---

AirCasting/Graph/AirCastingGraph.swift
AirCasting/Graph/External/ExternalGraphView.swift
AirCasting/Graph/GraphView.swift
AirCasting/Graph/StatisticsContainer/Controller/Interfaces/MeasurementsStatisticsInput.swift
AirCasting/Graph/StatisticsContainer/Controller/Interfaces/ScheduledTimer.swift
AirCasting/Graph/StatisticsContainer/Controller/MeasurementsStatisticsController.swift
AirCasting/Graph/StatisticsContainer/ViewModel/StatisticsContainerViewModel.swift
AirCasting/Graph/StatisticsContainer/ViewModel/StatisticsContainerViewModelable.swift
AirCasting/Map/AirMapView.swift
AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionCard.swift
AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionMapView.swift
AirCasting/SessionViews/SessionCardView.swift
AirCasting/SessionViews/SingleMeasurementView.swift
AirCasting/SessionViews/StatisticsContainerView.swift
AirCastingTests/Logic/Statistics/MeasurementsStatisticsControllerTests.swift
AppDelegate+Injection.swift

Added a mechanism to suspend timers scheduled in `MeasurementsStatisticsController` so that they are not firing when the user is not in map or graph view.

Overfiring timer for statistics container fixed

---

AirCasting/CoreData/NSManagedObjectContext+Utils.swift
AirCasting/Dashboard/DashboardView.swift
AirCasting/Dashboard/RefreshControl.swift
AirCasting/Dashboard/Reordering/ReorderingDashboard.swift
AirCasting/Dashboard/Reordering/ReorderingDashboardViewModel.swift
AirCasting/Dashboard/SessionListView.swift
AirCasting/MainTabBarView.swift
AirCasting/Services/DownloadMeasurmentsService.swift
AirCasting/Utils/Strings.swift

https://trello.com/c/JJclGtOq
We want to show progress view when we are downloading measurements for followed session when user enters the app, because sometimes it can take a significant time.
I noticed that in reordering dashboard we are showing a card for deleted session so that got fixed as well

Show measurements downloading progress in following tab

---

AirCasting/BluetoothSession/BluetoothSessionRecordingController.swift
AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift

Adding one more check because when the phone freezes on session creation confirmation screen and a user presses a button more than once it is possible that more than one session is created

Make sure there can be only one session being recorded

---

AirCasting/SessionViews/ShareSession/ShareSessionViewModel.swift
AirCasting/Utils/InAppAlerts.swift
AirCasting/Utils/Strings.swift

The aim was not to allow users to get a link when sharing a fixed session which is gathering data and no stream can be seen.

Unless there are no streams, show alert.

---

AirCasting/Dashboard/DashboardView.swift

**Goal:**
Now, when user logs in to the app, there is no indication of sync from the UI perspective.
Goal was to add this spinner, and cover possible future cases when sync could be triggered from code.

Show refresh control when sync was trigerred from code.

---

AirCasting.xcodeproj/project.pbxproj
AirCasting/SessionViews/SessionHeaderView.swift
AirCasting/SessionViews/SessionTime.swift
AirCasting/SessionViews/SessionTimeView.swift

Turn out active session end time was updating only because the whole session card was updating when statistics were calculated, which was happening even if user was not in map/graph view. When we fixed excessive statistics updating, session end time stopped updating.
I added new DynamicSessionEndTime view for active sessions which observes stream and shows end time based on the last measurement time. It has to be done like that because before the session is finished it's end time is nil.
https://trello.com/c/t3GQHAVF

Fix end time updating for active session

---

AirCasting/BluetoothSession/MeasurementsSavingService.swift
AirCasting/Graph/AirCastingGraph.swift

Problem is the line itself we use in the graph...
Below attaching the compression of the classic `Linear` style and the lowest value of `cubic` (which we currently have).
**Idea**
To fully get rid of that backwards thing, we would need to use a `linear` style. It is not optimal, as the `cubic` looks nicer, so we are lowering its intensity to the minimum which will help a lot here.

Line going backwards 

---

AirCasting/SessionViews/SessionCardView.swift

https://trello.com/c/jolWIKyL/863-mobile-active-app-doesnt-auto-navigate-to-mobile-active-tab-after-starting-a-mobile-active-session

Auto navigate to mobile active 

---

AirCasting/CoreData/NSManagedObjectContext+Utils.swift

The change was made to fix a bug that was causing the app to crash during session averaging while the was a followed session.
https://trello.com/c/2uiHArCd

Refresh objects in the context before saving

---

AirCasting/Utils/Strings.swift

https://trello.com/c/HpN9VyAO/885-settings-clear-sd-card-update-text-so-it-reads-clear-airbeam-data-storage

Rename settings - Clear SD to Clear AirBeam data storage.
