- AirCasting.xcodeproj/project.pbxproj
- AirCasting/SessionCell.swift
**Summary**
- Added single session view. 
- All data is mocked 
- Buttons aren't working.
> Session cell

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/AirCastingApp.swift
- AirCasting/ButtonStyles/BlueButtonStyle.swift
- AirCasting/Extensions/Array.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Graph/HeatmapSettings.swift
- AirCasting/Graph/MultiSlider.swift
- AirCasting/Graph/PollutionGraph.swift
- AirCasting/Graph/StatisticsContainer.swift
- AirCasting/Session/EditButton.swift
- AirCasting/Session/SessionCell.swift
- AirCasting/Session/SessionHeader.swift
**SUMMARY**
- There's a heatmap setting added, 
- Changing values on heatmap are reflected on slider and graph, 
- The Heatmap settings is simplified version, it'll be changed in the future to look like in the designs, 
- The simplified version of heatmap settings is different from the Android app - it's customized for apple's design guidelines.
> Graph part2

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/AirCastingApp.swift
- AirCasting/Dashboard.swift
- AirCasting/EmptyDashboard.swift
- AirCasting/MainTabBarView.swift
- AirCasting/Session.swift
- AirCasting/Session/Graph/GraphView.swift
- AirCasting/Session/Map/AirMapView.swift
**SUMMARY**
- there's a list of sessions in dashboard,
- Picker doesn't work yet, the "following" section is selected and can't be changed, 
- all the  data is hardcoded.
> Session list

- AirCasting/AuthViews/AuthErorrHandling.swift
- AirCasting/AuthViews/CreateAccountView.swift
- AirCasting/AuthViews/SignInView.swift
Changed "username" to "profile name" on UI.
> Changed username to profile name on UI

- AirCasting/CoreData/NSManagedObjectContext+Utils.swift
- AirCasting/CreateSessionViews/ABConnectedView.swift
- AirCasting/CreateSessionViews/AddNameAndTagsView.swift
- AirCasting/CreateSessionViews/ChooseSessionTypeView.swift
- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/CreateSessionViews/ConnectingABView.swift
- AirCasting/CreateSessionViews/PowerABView.swift
- AirCasting/CreateSessionViews/SelectDeviceView.swift
- AirCasting/CreateSessionViews/SelectPeripheralView.swift
- AirCasting/CreateSessionViews/TurnOnBluetoothView.swift
- AirCasting/MainTabBarView.swift
Now after confirming creating session user goes back to dashboard view.
> Return to dashboard after creating session

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/CoreData/NSManagedObjectContext+Utils.swift
- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/Graph/Graph.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Map/GoogleMapView.swift
- AirCasting/Map/LocationTracker.swift
- AirCasting/MicrophoneSession/MicrophoneManager.swift
- AirCasting/Models/Session+Mock.swift
- AirCasting/Models/SessionContext.swift
- AirCasting/SessionViews/ChartView.swift
- AirCasting/SessionViews/HeatmapSettingsView.swift
- AirCasting/SessionViews/MeasurementDotView.swift
- AirCasting/SessionViews/MultiSliderView.swift
- AirCasting/SessionViews/SessionCellView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
**SUMMARY**
The dot displayed next to the measurement has a different color depending on the measurement. 
**CODE**
1. I refactored names - from "values" to "thresholds".
2. App was creating empty mocked sessions without UUIDs when entering map or graph view. I "fixed" that bug for now - it'll be fixed for real when we'll be using real sessions instead of mocked on map and graph view. 
3. When creating a new mic session I check if thresholds for dB stream exist in database, if not I save hardcoded thresholds --> mic thresholds values need to be changed after implementing calculating measurement to dB
4. I created MeasurementDotView where I'm creating dot view and color it - the color depends on threshold intervals and measurement value. 
5. On sessionHeaderView I fetch all the thresholds …
> Measaurement dot colors on mic session

- AirCasting/CoreData/CoreDataHook.swift
- AirCasting/CoreData/MeasurementStreamEntity.swift
- AirCasting/CoreData/PersistenceController.swift
- AirCasting/CoreData/SessionEntity.swift
- AirCasting/Dashboard/DashboardView.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/MainTabBarView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Map/PathPoint.swift
- AirCasting/MicrophoneSession/MicrophoneManager.swift
- AirCasting/Models/Session+Mock.swift
- AirCasting/SessionViews/MeasurementDotView.swift
- AirCasting/SessionViews/SessionCellView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
The microphone session doesn't resume after interruption
Sessions are not fetched to dashboard until user chooses other tab than "mobileActive"
> Newest session is at the bottom in Mobile dormant in the dashoboard

- AirCasting.xcodeproj/project.pbxproj
Changed Provisioning profile to AirCasting ad hoc distribution.
> Fix signing

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/Models/MeaurementStreamExtension.swift
- AirCasting/SessionViews/CharEntriesCreator.swift
- AirCasting/SessionViews/ChartEntriesCreator.swift
- AirCasting/SessionViews/ChartView.swift
- AirCasting/SessionViews/SessionCellView.swift
Averaged values for measurements are displayed on a chart.
For mobile session there are 9 averages for each minute, and for fixed session there are 9 averages for each hour.
When there are no measurements for given minute or hour, there is no dot on the chart for that time period.
Dots on the chart are coloured depending on threshold values.
Labels under the chart view still need to be added in another PR.
> Chart view

- AirCasting/CreateSessionViews/CreateSessionDetailsView.swift
https://trello.com/c/uEXckYam/72-fixed-wifi-session-if-wifi-ssid-and-password-is-empty-user-cant-go-to-the-confirmationview-there-should-be-alert-informing-why
> wifi_popup

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/Graph/AirCastingGraph.swift
- AirCasting/Graph/Graph.swift
- AirCasting/Graph/GraphRenderers.swift
I added midnight lines to the graph. I don't know why limit lines don't reach the top, couldn't find the reason for that. If you have any ideas, please share :)
> Midnight lines

- AirCasting/Dashboard/EmptyDashboardView.swift
- AirCasting/MainTabBarView.swift
- AirCasting/RootAppView.swift
- AirCasting/Settings/MyAccountView.swift
- AirCasting/Settings/MyAccountViewSignOut.swift
https://trello.com/c/5pdbqezX/109-empty-dashboard-view-button-record-new-session
> Dashboard flow changed and button deleted

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/AuthViews/CreateAccountView.swift
- AirCasting/AuthViews/SignInView.swift
- AirCasting/AuthViews/UserDefaultsProtocol.swift
- AirCasting/RootAppView.swift
https://trello.com/c/FXx9oKZc/115-show-progress-bar-on-login-create-account-screen-only-when-onboarding-screen-happens
new branch to the same troll ticket because of the conflicts that I was not been able to resolve :/
> added what's needed - changes to onboarding progress

- AirCasting/Dashboard/DashboardView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
https://trello.com/c/l3z9JbNm/138-edit-session-button-tappable-space-needs-to-be-bigger
> added clear rectangle over button which expanded space

- AirCasting/Dashboard/DashboardView.swift
- AirCasting/Settings/BackendSettingsView.swift
- AirCasting/Settings/MyAccountViewSignOut.swift
- AirCasting/Settings/SettingsView.swift
What was done:
Title and fonts and colours were changes to be the same as on design.
Additional: I have changed the main "Dashboard" title color to dark Blue/
https://trello.com/c/CNDhTlVP/127-ui-settings-view-has-different-fonts-than-it-supposed-to-have
> added changes to settings and main Dashboard title

- AirCasting/Dashboard/DashboardView.swift
Develop not working SessionCellView name -> SessionCartView and working now
> fix to develop

- AirCasting/AuthViews/KeychainStorage.swift
- AirCasting/Settings/MyAccountViewSignOut.swift
- AirCasting/Utils/Strings.swift
What was done:
When someone enters the My account section in the settings, he is able to see he's email there
https://trello.com/c/HeY148lO/165-myaccountviewsignout-sign-out-name
> added proper username when logging out

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/AuthViews/LifeTimeEventsProvider.swift
> Develop fix two

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/Extensions/Array+SensorThreshold.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Map/GoogleMapView.swift
- AirCasting/MicrophoneSession/MicrophoneManager.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/ChartView.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/SessionViews/StreamsView.swift
Sth happened with the previous PR so I'm creating a new one with fixes from Pawełs CR.
> Fix threshold

- AirCasting/Onboarding/GetStarted.swift
- AirCasting/Utils/Strings.swift
What was done:
Changes made to Michael request
https://trello.com/c/lu2R2Pws
> onboarding changes to tested

- AirCasting/Models/MeaurementStreamExtension.swift
- AirCasting/Models/SessionExtension.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/HeatmapSettingsView.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/SessionViews/StreamsView.swift
- AirCasting/Utils/Strings.swift
**SUMMARY**
Dormant sessions should display average values.
> Average measurements for dormant sessions

- AirCasting/Onboarding/PrivacyOnboarding.swift
What was done:
ScrollView added to be able to see whole content on for exp. iPhoneSE2
https://trello.com/c/VXYtfioc/204-intro-wizard-privacy-cant-scroll-read-privacy-policy
> privacy policy scrollable

- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/Utils/Strings.swift
What was done:
Changed text 
Added progressView as on android
https://trello.com/c/lED2U4Ia/206-fixed-session-wizard-match-screens-to-android-are-you-ready-screen
> match Are You Ready? screen

- AirCasting/Dashboard/EmptyDashboardView.swift
- AirCasting/Utils/Strings.swift
What was done:
Changed some text
Added 'Did You know' TextField - it does not have correct photo yet, but this will be changes in the future
https://trello.com/c/OWBnGx5V/190-mobile-active-default-match-the-default-screen-to-the-android
> match empty dashboardView with android

- AirCasting/AirCastingApp.swift
- AirCasting/AuthViews/UserAuthenticationSession.swift
- AirCasting/CoreData/MeasurementStreamStorage.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/MainTabBarView.swift
- AirCasting/MicrophoneSession/MicrophoneManager.swift
- AirCasting/RootAppView.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/SessionViews/StreamsView.swift
- AirCasting/Utils/Strings.swift
What was done:
Finish recording in now available through action Menu.
https://trello.com/c/CEL1yPL5/186-mobile-active-buttons
> Changes to finish recording on mobile session

- AirCasting/Dashboard/EmptyDashboardView.swift
- AirCasting/RootAppView.swift
> develop fix - going to next screen

- AirCasting/Dashboard/EmptyDashboardView.swift
https://trello.com/c/OWBnGx5V/190-mobile-active-default-match-the-default-screen-to-the-android
Changes to dashboard in which text goes to very small
> Dashboard screen

- AirCasting/Utils/Strings.swift
https://trello.com/c/157z8IBZ/209-intro-wizard-our-privacy-policy-text-is-incomplete
What was done:
Privacy policy copied from the website
> Privacy Policy completing

- AirCasting/CreateSessionViews/PowerABView.swift
Changes to the ticket that came back from review:
https://trello.com/c/itTX3vX1/192-fixed-mobile-config-wizard-power-on-your-airbeam-remove-subtext-beginning-if-using
> config wizard > "Power on your AirBeam

- AirCasting/SessionViews/SessionCartView.swift
follow and unfollow session button appeaed now
> follow fix

- AirCasting/AuthViews/UserSettings.swift
- AirCasting/Settings/SettingsView.swift
The switch was starting from the `On` position which was not reflecting actual setting state.
> Fixed contribute switch

- AirCasting/CoreData/MeasurementStreamStorage.swift
[Trello](https://trello.com/c/94mcyT22)
Take a look. I think this is already how it works, just removed the unused code.
> Removed dead logic for locally updating session end time

- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/RootAppView.swift
- AirCasting/Utils/Strings.swift
UI changes to wifi name - added spaces
Small cleanup too 
https://trello.com/c/5MO5s7Of/212-ui-bugs
> UI changes

- AirCasting/Dashboard/DashboardView.swift
- AirCasting/Dashboard/EmptyDashboardView.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Onboarding/AirBeamOnboarding.swift
- AirCasting/Onboarding/GetStarted.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/Utils/Strings.swift
What was done:
Changed images layout
Added images to empty card
Added background etc.
https://trello.com/c/eWaUNNiv/213-formatting-of-various-airbeam-images
> UI and images - changes

- AirCasting/Utils/Strings.swift
Added spaces to wifi network
https://trello.com/c/5MO5s7Of/212-ui-bugs
> added spaces to wifi name

- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/CreateSessionViews/CreateSessionDetailsView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/0Ii0jCDy/223-fixed-mobile-wizard-start-recording-screen-update-text-formatting
> Wizard text formatting

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/AirCastingApp.swift
- AirCasting/Dashboard/DashboardView.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/MainTabBarView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/MicrophoneSession/MicrophoneManager.swift
- AirCasting/RootAppView.swift
- AirCasting/SessionStopping/MicrophoneSessionStopper.swift
- AirCasting/SessionStopping/SessionStoppable.swift
- AirCasting/SessionStopping/SessionStoppableFactory.swift
- AirCasting/SessionStopping/StandardSesssionStopper.swift
- AirCasting/SessionStopping/SyncTriggeringSesionStopperProxy.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
* Made ending synchronization [polymorphic](https://en.wikipedia.org/wiki/Polymorphism_(computer_science))
* We need to sort out dependency injection...
> Fixed crash when ending BT sessions

- AirCasting/CoreData/SessionEntity.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/SessionCartView.swift
It was impossible to select a measurements stream on graph or map view, the view went back to the dashboard. 
Task: https://trello.com/c/RnoCe7eH/124-selecting-streams-on-map-graph-view
> Fix selectstream

- AirCasting/SessionViews/SessionHeaderView.swift
https://trello.com/c/wKtdwXCQ/230-dashboard-cards-menu-button-hard-to-tap-menu-button
> Bigger tappable spacer

- AirCasting/Info.plist
https://trello.com/c/bX7x3uUD/228-block-night-mode
> disabaled dark mode

- AirCasting/CreateSessionViews/WifiPopupView.swift
https://trello.com/c/Lds9qOub/231-fixed-wizard-wifi-bold-network-name-in-aircasting-blue-dont-bold-network
> unbolded network text

- AirCasting/SessionViews/SessionCartView.swift
There were two maps button instead of graph and map -> now it should be ok
> changed map to graph

- AirCasting/ABConnector/BluetoothManager.swift
- AirCasting/CoreData/MeasurementStreamStorage.swift
- AirCasting/CoreData/NSManagedObjectContext+Utils.swift
- AirCasting/MobilePeripheralSessionManager.swift
- AirCasting/RootAppView.swift
- AirCasting/SessionStopping/MicrophoneSessionStopper.swift
- AirCasting/SessionStopping/SessionStoppableFactory.swift
- AirCasting/SessionStopping/StandardSesssionStopper.swift
https://trello.com/c/rKj2y6x7/220-finish-bluetooth-session
> Finish ab session

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/MicrophoneSession/MicrophoneManager.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/Utils/Constants.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/52VOtYg4/142-change-loading-view-for-mic-sessions
What was done:
The goal is to differentiate different session and show different views
> differentiate views for sessions

- AirCasting/CoreData/SessionEntity.swift
- AirCasting/Models/SessionExtension.swift
- AirCasting/SessionViews/SessionHeaderView.swift
Removed for now unused button from session menu
> changes to action menu

- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/SessionViews/StreamsView.swift
- AirCasting/Utils/Strings.swift
What was done:
Michael in comments said the we need to make some changes - I know that iffffying is not pretty but don't have better ideas for know :/
https://trello.com/c/zvSTCjIu/45-differences-design-android-app-vs-ios-app
> changed text depends on the state - sessions

- AirCasting/APICommunicator/CreateSessionAPI.swift
Now fixed sessions appear on crowd map 🥳
> Upload fixed sessions

- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
https://trello.com/c/QjomS94U/242-wizard-mobile-fixed-outdoor-fixed-indoor-are-you-ready-screen-text-flow-is-incorrect
> wizard confirm screen changed

- AirCasting/CreateSessionViews/CreateSessionDetailsView.swift
Fixed creating mic sessions for build #25
> build #25 

- AirCasting/CoreData/PersistenceController.swift
- AirCasting/CreateSessionViews/CreateSessionDetailsView.swift
Changed mic DefaultMicThresholdsValues to a proper ones
> Change DefaultMicThresholdsValues

- AirCasting/Dashboard/EmptyDashboardButtonView.swift
- AirCasting/Dashboard/EmptyFixedDashboardView.swift
- AirCasting/Dashboard/EmptyMobileDashboardView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/ADhWO5Uc/243-following-blank-fixed-new-profile-default-view-should-look-like-android
> Change dashboard texts for fixed followed

- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/QjomS94U/242-wizard-mobile-fixed-outdoor-fixed-indoor-are-you-ready-screen-text-flow-is-incorrect
What was done:
Text was doubled because of some unwanted var so it is deleted now.
> added to string dot and cleanup

- AirCasting/Graph/StatisticsContainer/ViewModel/StatisticsContainerViewModel.swift
- AirCasting/SessionViews/SessionCartView.swift
As requested:
https://trello.com/c/4bWTFHvZ
> Removed units from stats container

- AirCasting/Map/GoogleMapView.swift
- AirCasting/Map/LocationTracker.swift
- AirCasting/Utils/Constants.swift
**Task:** https://trello.com/c/jv3Hk6EG/227-mobile-map-improve-mapping-visualization
Added autozoom based on what Android has, it searches for the most extreme long/lat coordinates, adds some padding, and displays the map accordingly. 
Although it's not entirely fixed, I'd like to send a build for Michael to test.
> Fixed zoom for map

- AirCasting/SessionViews/ABMeasurementsView.swift
https://trello.com/c/vW8SzxdU/261-mobile-dormant-unexpanded-parameters-arent-displayed
> Parameters on dormant

- AirCasting/CoreData/SessionEntity.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/SingleMeasurementView.swift
https://trello.com/c/kT13LHxW/247-change-streams-order
> changed stream order

- AirCasting.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- AirCasting/SessionViews/SessionHeaderView.swift
The bug: https://trello.com/c/RmN7eePA/74-time-displayed-on-top-of-the-session-is-incorrect
PS. thanks Janek ;)
> Changed formatter time zone

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/Utils/TimeConversion.swift
https://trello.com/c/7ktdjPxZ/260-use-24-hr-time
What was done:
System has the settings which enforces all apps to use 24 or 12 format. For now we should use only 24h format so the conversion needs to be made - and that was the idea of this task.
TO TEST:
Go to system settings and change format to 12 seeing if the time on the session cart changes or not
> time 24h format

- AirCasting/SessionViews/ChartView.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/T5EJqaY9/238-mobile-active-following-dashboard-chart-make-it-look-work-like-android
What was done:
Chart to match android - following point which were done here are on the ticker
> chart to match android

- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Map/GoogleMapView.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/SessionCartView.swift
What was done:
There was a delay on especially long sessions on the map zooming and changing streams.
Should work better compering to develop now.
https://trello.com/c/9kOgl6ZX/278-mobile-active-mobile-dormant-map-pan-zoom-there-is-a-delay-between-pan-zoom-actions-response
> map improvement

- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/EGFDCPSp/282-all-tabs-cards-missing-sensor-package-name-wrong-sensor-package-name
> Add sensor name

- AirCasting/Models/SessionExtension.swift
https://trello.com/c/kT13LHxW/247-change-streams-order
> fix streams of AirBeam2/1

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/CreateSessionViews/SelectDeviceView.swift
- AirCasting/Dashboard/EmptyDashboardButtonView.swift
- AirCasting/MainTabBarView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/0HwaqLLe/252-differentiate-empty-onboarding-screens-for-mobile-fixed
> Onboarding changes differrences

- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/SessionsSynchronization/Adapters/Services/SessionDownloadService.swift
- AirCasting/SessionsSynchronization/Adapters/Services/SessionUploadService.swift
- AirCasting/Utils/TimeConversion.swift
https://trello.com/c/RmN7eePA/74-time-displayed-on-top-of-the-session-is-incorrect
> sessions time zone changed to UTC

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/ABConnector/AirBeam3Configurator.swift
- AirCasting/CreateSessionViews/ABConnectedView.swift
- AirCasting/CreateSessionViews/ChooseCustomLocationView.swift
- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/CreateSessionViews/ConnectingABView.swift
- AirCasting/CreateSessionViews/CreateSessionDetailsView.swift
- AirCasting/CreateSessionViews/SelectDeviceView.swift
- AirCasting/CreateSessionViews/SelectPeripheralView.swift
- AirCasting/CreateSessionViews/TurnOnBluetoothView.swift
- AirCasting/CreateSessionViews/TurnOnLocation/TurnOnLocationView.swift
- AirCasting/CreateSessionViews/WifiPopupView.swift
- AirCasting/Models/AirBeamCellularSessionCreator.swift
- AirCasting/Models/AirBeamFixedWifiSessionCreator.swift
Creating cellular AB session. 
https://trello.com/c/p07gVkJC/181-creating-fixed-cellular-session
> Create cellular session

- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/EGFDCPSp/282-all-tabs-cards-missing-sensor-package-name-wrong-sensor-package-name
For now (still) it needs to be handled somehow to show the right sensor name
> sensor name fix

- AirCasting/CreateSessionViews/ChooseCustomLocationView.swift
- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/CreateSessionViews/PlacePicker.swift
- AirCasting/Extensions/Date+Miliseconds.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Map/GoogleMapView.swift
https://trello.com/c/nsAKfJgj/277-wizard-fixed-outdoor-search-the-address-after-searching-for-address-and-submitting-location-isnt-updated
> PlacePicker fix

- AirCasting/CoreData/MeasurementStreamStorage.swift
- AirCasting/CoreData/SessionEntity.swift
- AirCasting/Extensions/Date+Miliseconds.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/SessionsSynchronization/Adapters/Services/SessionDownloadService.swift
- AirCasting/SessionsSynchronization/Adapters/Services/SessionUploadService.swift
https://trello.com/c/RmN7eePA/74-time-displayed-on-top-of-the-session-is-incorrect
For now, after a lot of testing, I think it should be working well. Please do not look at the graph, for now, I will focus on this on the other ticket, not to messed it up, and make it in small steps.
I have added there a code that results in logging out from the app without a crash. I know it is not perfect at all, but after thinking it could be easier for us and a better UX for the user. Please @pawelgil consider it, I am going to leave there a warning (It was working for me every time I logged out).
PS. Thank You @pawelgil for pair programming 😄
> time formatting in sessions header

- AirCasting/CoreData/PersistenceController.swift
- AirCasting/MainTabBarView.swift
- AirCasting/Services/DownloadMeasurmentsService.swift
... which was causing the app to freeze like crazy 🥶🧊🥶🧊🥶🧊
> MeasurementUpdatingService is now being run on background thread instead of main

- AirCasting/CreateSessionViews/SelectDeviceView.swift
https://trello.com/c/2FO8t6Om/305-bug-during-creating-a-mobile-session
> Disabling mobile session state

- AirCasting/Graph/AirCastingGraph.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
https://trello.com/c/DhHadEvW/304-graph-incorrect-time
> Handle right time graph

- AirCasting/SessionViews/ABMeasurementsView.swift
https://trello.com/c/Mb4Qkbho/306-mobile-active-spinner-not-shown-at-end-of-wizard
> added spinner to airBeam mobile

- AirCasting/SessionViews/ABMeasurementsView.swift
https://trello.com/c/GfTwzex6/235-mobile-active-wizard-complete-show-loading-indicator
> fix_text_session

- AirCasting/CoreData/MeasurementStreamStorage.swift
- AirCasting/Models/SessionCreator.swift
- AirCasting/Models/SessionExtension.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/Utils/Constants.swift
https://trello.com/c/Uc9JkpSN/313-ab3-mobile-active-mobile-dormant-inaccurate-timestamps
This fix should handle every case in the US so Michael I hope will be happy
> changed time to be always as your current time on the phone

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/ABConnector/AirBeam3Configurator.swift
- AirCasting/APICommunicator/CreateSessionAPI.swift
- AirCasting/Extensions/Date+Miliseconds.swift
- AirCasting/Graph/AirCastingGraph.swift
- AirCasting/Graph/GraphRenderers.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/SessionsSynchronization/Adapters/Services/SessionDownloadService.swift
- AirCasting/SessionsSynchronization/Adapters/Services/SessionUploadService.swift
- AirCasting/Utils/DataFormatters.swift
- AirCasting/Utils/TimeConversion.swift
https://trello.com/c/DhHadEvW/304-graph-incorrect-time
> Handle right time graph (after Paweł changes)

- AirCasting/Assets.xcassets/AircastingRed.colorset/Contents.json
- AirCasting/Assets.xcassets/AppIcon.appiconset/Contents.json
- AirCasting/Assets.xcassets/GraphGreen.colorset/Contents.json
- AirCasting/Assets.xcassets/GraphOrange.colorset/Contents.json
- AirCasting/Assets.xcassets/GraphRed.colorset/Contents.json
- AirCasting/Assets.xcassets/GraphYellow.colorset/Contents.json
https://trello.com/c/KebpcXW6/276-graph-remove-transparency-from-background-colors
> colors changed to match android style

- AirCasting/SessionViews/StatisticsContainerView.swift
https://trello.com/c/fbWq2j1G/275-stats-container-formatting
What was done here:
The number goes to the center
The container is now moved to the corner and the background is a bit smaller
> making container smaller and numbers formatting

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/TqnifbDR/321-lets-begin-text-formatting
> buttons and padding formatting

- AirCasting.xcodeproj/project.pbxproj
> build number to 39

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
https://trello.com/c/TqnifbDR/321-lets-begin-text-formatting
> spacing value changed to 25

- AirCasting/SessionViews/MultiSliderView.swift
https://trello.com/c/GnzrkJ3z/262-heat-legend-difficult-to-select-values-and-edit-them
> make heat mapbuttons more accesible, easier clickable

- AirCasting/CreateSessionViews/SelectDeviceView.swift
https://trello.com/c/aHMV5v4F/241-mobile-wizard-after-tapping-bluetooth-device-or-phone-microphone-move-to-the-next-screen
> removed choose button from wizard

- AirCasting/SessionViews/SessionHeaderView.swift
https://trello.com/c/wKtdwXCQ/230-dashboard-cards-menu-button-hard-to-tap-menu-button
> makes tappable space wider for menu button

- AirCasting/Utils/Strings.swift
https://trello.com/c/oAn5v0om/369-intro-wizard-2nd-screen-learn-more-correct-text
> text to match android - onboarding

- AirCasting/CoreData/PersistenceController.swift
- AirCasting/CoreData/SessionEntity.swift
> Assign session end time when finishing active sessions

- AirCasting/Dashboard/AirSectionPickerView.swift
- AirCasting/Dashboard/DashboardView.swift
> remove unused code from swiping between tabs

- AirCasting/ABConnector/AirBeamServices.swift
> Remove connection observer after it was used

- AirCasting/ABConnector/BluetoothManager.swift
To avoid fatal error when values count != 12
> Check if values count is 12

- AirCasting/Info.plist
https://trello.com/c/10SU94sN/405-location-services-permission-requests
Nothing else as decided on Scrum with Michael should be done in this ticket then text change
> updated text of location prompt

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/Graph/AirCastingGraph.swift
- AirCasting/Graph/AirCastingGraphSimplifier.swift
- AirCasting/Graph/Graph.swift
Now it matches mostly android algorithm and modes to structure graph line so it should be closer.
https://trello.com/c/aaVUAALc/357-graph-simplified-line-looks-strange
> new graph simplify

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/AuthViews/UserAuthenticationSession.swift
- AirCasting/RootAppView.swift
- AirCasting/SessionsSynchronization/Controller/SessionSynchronizationController.swift
- AirCasting/SessionsSynchronization/Controller/SessionSynchronizer.swift
- AirCasting/SessionsSynchronization/Controller/Utils/ScheduledSessionSynchronizerProxy.swift
- AirCasting/Settings/BackendSettingsView.swift
- AirCasting/Settings/MyAccountViewSignOut.swift
- AirCasting/Settings/SettingsView.swift
- AirCasting/Utils/ActivityIndicator.swift
- AirCasting/Utils/Strings.swift
- AirCasting/Utils/UserState.swift
https://trello.com/c/e10Aoee6/396-sync-app-prior-to-sign-out
> sync on logout

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/Info.plist
Co-authored-by: Jan Krzempek <jankrzempek@Jans-MBP.lan>
> App version 1.0.1

- AirCasting/AuthViews/UserSettings.swift
- AirCasting/Settings/SettingsView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/d2sZRTi8/387-settings-keep-screen-on
> added setings keepScreenOn

- AirCasting/Map/AirMapView.swift
- AirCasting/Map/GoogleMapView.swift
https://trello.com/c/QJGnphuq/398-mobile-active-map-when-first-entering-the-map-center-map-over-current-location
> center map over current location

- AirCasting/ABConnector/BluetoothManager.swift
- AirCasting/CreateSessionViews/SelectPeripheralView.swift
https://trello.com/c/56Q1NT8b/425-fix-bt-scanning
> Fix BT scanning

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/AirCastingApp.swift
- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/Dashboard/DashboardView.swift
- AirCasting/Dashboard/EmptyFixedDashboardView.swift
- AirCasting/Dashboard/EmptyMobileDashboardView.swift
- AirCasting/Dashboard/RefreshControl.swift
- AirCasting/MainTabBarView.swift
- AirCasting/SessionsSynchronization/Controller/SessionSynchronizer.swift
- GreenButtonStyle.swift
- Modules/AirCastingStyling/Sources/AirCastingStyling/BlueButtonStyle.swift
- Modules/AirCastingStyling/Sources/AirCastingStyling/Color.swift
- Modules/AirCastingStyling/Sources/AirCastingStyling/GreenButtonStyle.swift
* `RefreshControl` - a custom, pure SwiftUI component
* Pull to refresh implemented in dashboard for lists and empty views
Trello: https://trello.com/c/EwBBax6c
> Pull to refresh added

- AirCasting/Dashboard/RefreshControl.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/PETpDvou/432-mobile-dormant-fixed-update-pull-to-refresh-ui
> added text below spinner

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/CoreData/MeasurementStreamEntity.swift
- AirCasting/CoreData/PersistenceController.swift
- AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsView.swift
- AirCasting/Dashboard/RefreshControl.swift
- AirCasting/Graph/Graph.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/SessionViews/ThresholdSettings/ThresholdsSettingsView.swift
- AirCasting/SessionViews/ThresholdSettings/ThresholdsSettingsViewModel.swift
- AirCasting/Utils/Strings.swift
New version! 1.0.2
Build reset to 1.
---------> Firebase
> 1.0.2 to Firebase

- AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsView.swift
https://trello.com/c/MQepK0pv/431-config-wizard-fixed-wifi-text-updates
The aim of this PR is to make a one-liner with text containing password
> changes text to one line

- AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsView.swift
- AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsViewModel.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/tt4Cp7dS/442-1022-fixed-cant-record-fixed-session
Na mocy nieobecności wszystkich i tego, że trzeba fixować wersję AppStore - merguję.
> session fixed - fix 

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/Utils/FileLineReader/DefaultFileLineReader.swift
- AirCasting/Utils/FileLineReader/FileLineReader.swift
- AirCastingTests/FileLineReaderTests/FileLineReaderTests.swift
We needed a highly memory efficient way of reading files one by one in order to perform SD card synchronization. This PR provides an interface and an implementation for this.
I tested the performance and it looks like it's constant no matter the size of the file and is ~4KB
> FileLineReader introduced

- AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsView.swift
Now when you create mic session your continue button could be disabled and you could stuck..
> allow always mic sessions

- Gemfile.lock
- fastlane/Fastfile
- fastlane/README.md
* Security measures (git tree clean and on development branch)
* Automatic build no bump
* Automatic git branch + commit prepared (manual push still needed ofc)
> Lane name changed to Beta + improvements

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/CoreData/AirCasting.xcdatamodeld/AirCasting.xcdatamodel/contents
- AirCasting/CoreData/MeasurementStreamStorage.swift
- AirCasting/CoreData/SessionEntity.swift
- AirCasting/Dashboard/DashboardView.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Models/SessionExtension.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/DeleteView.swift
- AirCasting/SessionViews/SessionCartView.swift
- AirCasting/SessionViews/SessionCartViewModel.swift
- AirCasting/SessionViews/SessionCartViewModel/DefaultDeleteSessionViewModel.swift
- AirCasting/SessionViews/SessionCartViewModel/DeleteSessionViewModel.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/SessionsSynchronization/Controller/SessionSynchronizer.swift
- AirCasting/StreamSynchronizer/StreamRemover.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/HR617RIB/134-mobile-dormant-fixed-delete-session
> Delete sessions option

- AirCasting/ABConnector/SDSyncController.swift
- AirCasting/RootAppView.swift
- AirCasting/SDSync/SDCardMobileSessionsSavingService.swift
- AirCasting/SDSync/SDSyncViewModel.swift
- AirCasting/Utils/AveragingService.swift
https://trello.com/c/aTNYb3Uq
https://trello.com/c/En0L1G8I
> Sd sync averaging and sending mobile sessions to backend

- AirCasting.xcodeproj/project.pbxproj
For RELEASE and BETA we're not using fixed profiles and certs
> Code signing for RELEASE and BETA sorted

- AirCasting/SDSync/ViewsFlow/SDSyncingAB/SyncingABView.swift
https://trello.com/c/caxWvcY8/426-sync-sd-card-views
Only image align here - fix
> SD View align image well

- AirCasting/ABConnector/AirBeamConnectionController.swift
- AirCasting/ABConnector/ConnectingAirBeamServices.swift
- AirCasting/SDSync/ViewsFlow/SDSyncingAB/SDSyncViewModel.swift
> Disconnect AirBeam after sd card sync

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/ABConnector/BluetoothManager.swift
- AirCasting/ABConnector/SDCardAirBeamServices.swift
- AirCasting/ABConnector/SDSyncController.swift
- AirCasting/RootAppView.swift
- AirCasting/SDSync/ViewsFlow/SDSyncingAB/SDSyncViewModel.swift
- AirCasting/SDSync/ViewsFlow/SDSyncingAB/SyncingABView.swift
- AirCasting/Utils/Int+orOne.swift
- AirCasting/Utils/Strings.swift
Added progress indication to SD synchronization API. 
Note that this has not been tested in any way, putting it here because interfaces have changed.
> Sd sync progress indication

- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/SessionCartViewModel/DefaultSyncingMeasurementsViewModel.swift
https://trello.com/c/hADJtngF/452-mobile-dormant-expand-card-avg-values-arent-displayed-cant-map-or-graph-session
> fix bug with not displaying measurements

- AirCasting/CoreData/MeasurementStreamStorage.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/SessionViews/DeleteView.swift
- AirCasting/SessionViews/SessionCardView.swift
- AirCasting/SessionViews/SessionCartViewModel/DefaultDeleteSessionViewModel.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/SessionViews/StandaloneSessionCardView.swift
https://trello.com/c/HR617RIB/134-mobile-dormant-fixed-delete-session
Michael wanted in the latest comment
> added sync after delete

- AirCasting/Utils/Strings.swift
https://trello.com/c/ny1TZFtT/461-sync-wizard-update-syncing-screen-text
> updated text - Syncing screen

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/SDSync/ViewsFlow/SDRestartAB/SDRestartABView.swift
- AirCasting/SDSync/ViewsFlow/SDRestartAB/SDRestartABViewModel.swift
- AirCasting/SDSync/ViewsFlow/SDSyncComplete/SDSyncCompleteView.swift
- AirCasting/SDSync/ViewsFlow/SDSyncComplete/SDSyncCompleteViewModel.swift
- AirCasting/SDSync/ViewsFlow/SDSyncRootView/SDSyncRootView.swift
- AirCasting/SDSync/ViewsFlow/SDSyncRootView/SDSyncRootViewModel.swift
- AirCasting/SDSync/ViewsFlow/SDSyncSuccess/BackendSyncCompletedView.swift
- AirCasting/SDSync/ViewsFlow/SDSyncSuccess/BackendSyncCompletedViewModel.swift
- AirCasting/SDSync/ViewsFlow/SDSyncingAB/SDSyncViewModel.swift
- AirCasting/SDSync/ViewsFlow/SDSyncingAB/SyncingABView.swift
https://trello.com/c/wVV18c4e/453-sd-views-refactor
based on the comments from merged PR: https://github.com/HabitatMap/AirCastingiOS/pull/466
> changes to SD views

- AirCasting/SessionViews/StandaloneSessionCardView.swift
> Remove stopping function from finish and sync button

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
https://trello.com/c/nVHx8nDH/469-1037-lets-begin-button-sub-text-is-cut-off
> Button cut off - fix

- AirCasting/ABConnector/SDCardAirBeamServices.swift
- AirCasting/SDSync/ViewsFlow/SDSyncingAB/SDSyncViewModel.swift
> Fix clearing sd card after sync

- AirCasting/Graph/Graph.swift
- AirCasting/Graph/GraphView.swift
View was not updated with new entries as it should be, now it is!
https://trello.com/c/qIiK23Nh/472-103-7-mobile-dormant-graph-stream-not-graphed-accurately
> fix graph streams

- AirCasting/ABConnector/SDSyncController.swift
- AirCasting/RootAppView.swift
- AirCasting/SDSync/SDSyncFileValidationService.swift
- AirCasting/SDSync/SDSyncFileWritingService.swift
> Check files for corruption

- AirCasting/Graph/Graph.swift
It appeared that fix 1 was not enough, this fix everything
> fix graph streams - 2

- AirCasting/Settings/SettingsView.swift
https://trello.com/c/RNI5AFGL/475-app-info-space
> added space between version and build number

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/ABConnector/SDSyncController.swift
- AirCasting/APICommunicator/FixedSession.swift
- AirCasting/CoreData/MeasurementStreamStorage.swift
- AirCasting/Graph/Graph.swift
- AirCasting/MainTabBarView.swift
- AirCasting/RootAppView.swift
- AirCasting/SDSync/FixedSessions/SyncedMeasurementsDownloadingService.swift
- AirCasting/SDSync/ViewsFlow/ClearingSDCard/ClearingSDCardViewModel.swift
- AirCasting/Services/DownloadMeasurmentsService.swift
- AirCasting/Services/UpdateSessionParams.swift
> SD Sync download measurements for fixed sessions after sync

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/CoreData/MeasurementStreamEntity.swift
- AirCasting/Extensions/SensorThreshold.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Models/ThresholdsValue.swift
- AirCasting/SessionViews/ThresholdSettings/ThresholdsSettingsView.swift
- AirCasting/SessionViews/ThresholdSettings/ThresholdsSettingsViewModel.swift
It's an old code from here: https://github.com/HabitatMap/AirCastingiOS/pull/433 with fixed from CRs.
> Change ThresholdsValue to struct

- Gemfile.lock
- fastlane/Fastfile
- fastlane/Pluginfile
Added "BETA" badge to app icon for beta releases:
> Added badge to beta lane

- AirCasting/SessionViews/ABMeasurementsView.swift
- AirCasting/SessionViews/SessionCardView.swift
FOR ITERATION 1
https://trello.com/c/2wpv0AXi/473-dashboard-increase-space-between-parameter-values-graph-map-buttons
> Spacing between map/graph button and parameters

- .gitignore
- fastlane/Fastfile
Note that you'll need to place AuthKey.p8 inside the fastlane directory and update your .env file to include:
APPSTORE_KEY_ID = ...
APPSTORE_ISSUER_ID = ...
> Fastfile and gitignore adjusted for appstore api key use

- AirCasting/SessionViews/SessionHeaderView.swift
https://trello.com/c/NEEa5bMK/482-following-remove-options-button-from-cards
> when following section - no menu

- AirCasting/FeatureFlags/FeatureFlagProvider.swift
- AirCasting/FeatureFlags/FeatureFlagProviders/DefaultFeatureFlagProvider.swift
- AirCasting/FeatureFlags/FeatureFlagProviders/FirebaseFeatureFlagProvider.swift
Already present on firebase config backend
> Feature flag for notes added

- AirCasting/Settings/MyAccountViewSignOut.swift
- AirCasting/Utils/InAppAlerts.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/U96fcBxM/490-handle-logging-out-offline
> Handling logout without internet

- AirCasting/AuthViews/SignInView.swift
- AirCasting/CreateSessionViews/ABConnectedView.swift
- AirCasting/CreateSessionViews/ChooseCustomLocationView.swift
- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/CreateSessionViews/ConnectingABView.swift
- AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsView.swift
- AirCasting/CreateSessionViews/PowerABView.swift
- AirCasting/CreateSessionViews/TurnOnBluetoothView.swift
- AirCasting/ForgotPassword/InterfaceAdapters/DefaultForgotPasswordViewModel.swift
- AirCasting/Onboarding/AirBeamOnboarding.swift
- AirCasting/SDSync/ViewsFlow/BackendSyncCompleted/BackendSyncCompletedView.swift
- AirCasting/SDSync/ViewsFlow/SDRestartAB/SDRestartABView.swift
- AirCasting/SDSync/ViewsFlow/SDSyncComplete/SDSyncCompleteView.swift
- AirCasting/SDSync/ViewsFlow/SDSyncUnplugAB/UnplugABView.swift
- AirCasting/SDSync/ViewsFlow/SDSyncingAB/SyncingABView.swift
- AirCasting/SessionViews/DeleteView.swift
- AirCasting/SessionViews/EditViewModal.swift
- AirCasting/SessionViews/ShareView.swift
- AirCasting/Settings/BackendSettingsView.swift
- AirCasting/Settings/MyAccountView.swift
- AirCasting/Settings/MyAccountViewSignOut.swift
- AirCasting/Utils/InAppAlerts.swift
- AirCasting/Utils/OfflineAlert.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/qobMnNDl/492-refactor-strings
> Strings struct - refactor 

- AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsView.swift
- AirCasting/CreateSessionViews/CreateSessionDetails/CreateSessionDetailsViewModel.swift
https://trello.com/c/rUzKLjUL/493-do-not-allow-empty-name
> Session name is blank

- AirCasting/ABConnector/ConnectingAirBeamServices.swift
- AirCasting/Map/LocationTracker.swift
- AirCasting/SDSync/FixedSessions/SyncedMeasurementsDownloadingService.swift
Handled a few warnings from our app.
The TESTING PURPOSE warning was deleted because it resulted being a working version
> handle our warnings

- AirCasting/Models/SessionExtension.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/5EgQCc2r/494-mobile-dormant-fixed-card-menu-button-small-changes
> Order of buttons - changed 

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/Map/AirMapView.swift
- AirCasting/Map/GoogleMapView.swift
- AirCasting/Map/style.json
https://trello.com/c/44pmKo80/393-update-google-maps-so-they-match-or-closely-resemble-the-style-used-on-the-ac-website
> match google maps with AC webiste

- AirCasting/Map/GoogleMapView.swift
https://trello.com/c/jGESXCgy/501-maps-missing-center-map-button
> center map button - improved

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/AuthViews/UserSettings.swift
- AirCasting/CoreData/MeasurementStreamEntity.swift
- AirCasting/Graph/Graph.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/SessionViews/SingleMeasurementView.swift
- AirCasting/Settings/SettingsView.swift
- AirCasting/Utils/Constants.swift
- AirCasting/Utils/Strings.swift
- AirCasting/Utils/TemperatureConverter.swift
* Add settings for converting temperature to celsius
* Implement conversion to celsius on UI level
https://trello.com/c/y2GtuRuw
> Convert to celcius

- AirCasting/CoreData/MeasurementStreamStorage.swift
- AirCasting/Graph/Graph.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Map/GoogleMapView.swift
- AirCasting/Map/MapNotesViewModel.swift
- AirCasting/Notes/EditNote/EditNoteViewModel.swift
- AirCasting/Notes/EmptyNotesHandler.swift
- AirCasting/Notes/NotesHandler.swift
- AirCasting/SessionViews/SessionCardView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/SingleSessionSynchronizer/SessionUpdateService.swift
https://trello.com/c/JP3hgYVA/486-mobile-active-add-a-note-edit-note
> [to MAIN branch] Edit note - server side

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/APICommunicator/CreateSessionAPI.swift
- AirCasting/CoreData/MeasurementStreamStorage.swift
- AirCasting/CoreData/PersistenceController+Database.swift
- AirCasting/CoreData/Session.swift
- AirCasting/Graph/AirCastingGraph.swift
- AirCasting/Graph/Graph.swift
- AirCasting/Graph/GraphView.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Map/GoogleMapView.swift
- AirCasting/Map/MapNotesViewModel.swift
- AirCasting/Notes/EditNote/EditNoteViewModel.swift
- AirCasting/Notes/EmptyNotesHandler.swift
- AirCasting/Notes/NotesHandler.swift
- AirCasting/SessionViews/SessionCardView.swift
- AirCasting/SessionViews/SessionHeaderView.swift
- AirCasting/SessionsSynchronization/Adapters/DataStore/SessionSynchronizationDatabase.swift
- AirCasting/SessionsSynchronization/Controller/Interfaces/SessionDownstream.swift
- AirCasting/SessionsSynchronization/Controller/Interfaces/SessionSynchronizationStore.swift
- AirCasting/SessionsSynchronization/Controller/Interfaces/SessionUpstream.swift
- AirCasting/SessionsSynchronization/Controller/Utils/SessionsSynchronizationStoreDataConverter.swift
- AirCasting/SessionsSynchronization/Database/DatabaseNote.swift
- AirCasting/SessionsSynchronization/Database/DatabaseSession.swift
- AirCasting/SingleSessionSynchronizer/SessionUpdateService.swift
Download:
Fetching data from the server and encoding it trough 3 layers. After that, saving notes to CoreDatawhich are connected to the specified session.
Upload:
Fetching data from Core Data and coding it trough 3 layers. After that, sending it to server inside the session struct.
> [MAIN] Note upload and download - server side.

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/CoreData/AirCasting.xcdatamodeld/.xccurrentversion
- AirCasting/CoreData/AirCasting.xcdatamodeld/AirCasting v2.xcdatamodel/contents
NoteEntity was added to the Core Data model. It consists of five attributes and has a session relation.
> Core Data - model migration

- AirCasting.xcodeproj/project.pbxproj
- AirCasting.xcworkspace/xcshareddata/swiftpm/Package.resolved
- AirCasting/Notes/AddNote/AddNoteView.swift
- AirCasting/Notes/AddNote/AddNoteViewModel.swift
- AirCasting/Notes/EditNote/EditNoteView.swift
- AirCasting/Notes/EditNote/EditNoteViewModel.swift
- AirCasting/Notes/NotesTextView.swift
- AirCasting/SingleSessionSynchronizer/SessionUpdateService.swift
- AirCasting/Utils/Strings.swift
- AirCasting/Utils/TextView.swift
Added custom TextView for note.
Also fixed editing note when there are no tags or the session is active during editing.
https://trello.com/c/3l0uspen/509-note-text-field-improved-edit-note-fix
> TextView - place for note content

- AirCasting/SessionViews/ABMeasurementsView.swift
https://trello.com/c/Jzmj9B7B/497-fix-ui-alignment-airbeam-session
Align SessionLoadingView to the left and top.
> Alligned AirBeam image - loading view.

- AirCasting/MicrophoneSession/MicrophoneManager.swift
- AirCasting/SessionStopping/SessionStoppableFactory.swift
https://trello.com/c/MEG58Ula/508-cannot-finish-mic-session-disable-mapping-on
> Microphone session - disable mapping ON.

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/Graph/StatisticsContainer/Adapters/Array+MeasurementStatistics.swift
- AirCasting/Graph/StatisticsContainer/Adapters/ConveringStatisticsDataSourceDecorator.swift
- AirCasting/Graph/StatisticsContainer/Adapters/GraphStatsDataSource.swift
- AirCasting/Graph/StatisticsContainer/Adapters/MapStatsDataSource.swift
- AirCasting/Graph/StatisticsContainer/Controller/Interfaces/MeasurementStatisticsTypes.swift
- AirCasting/Graph/StatisticsContainer/Controller/Interfaces/MeasurementsStatisticsDataSource.swift
- AirCasting/Graph/StatisticsContainer/Controller/MeasurementsStatisticsController.swift
- AirCasting/Graph/StatisticsContainer/ViewModel/StatisticsContainerViewModel.swift
- AirCasting/SessionViews/SessionCardView.swift
This is a draft code only to show how it can be done using polymorphism instead of conditionals. It needs:
* Fixing commented out preview part
* Testing if it works ;)
> Polymorphic approach to F<->C conversion in stats container

- AirCasting/MobilePeripheralSessionManager.swift
> Fix session mapping

- AirCasting/Models/AirBeamFixedWifiSessionCreator.swift
> Fix creating indoor sessions

- Readme.md
- fastlane/Fastfile
- fastlane/README.md
Added release_update lane to fastfile for updating RC builds
> Release update lane

- AirCasting.xcodeproj/xcshareddata/xcschemes/AirCasting.xcscheme
- AirCasting/AirCastingApp.swift
- AirCasting/AuthViews/UserAuthenticationSession.swift
- AirCasting/CoreData/SessionStorage.swift
- AirCasting/MainTabBarView.swift
- AirCasting/SessionViews/SessionCartViewModel/DefaultSyncingMeasurementsViewModel.swift
- AppDelegate+Injection.swift
- AppDelegate.swift
Clean boot option added to environment variables.
When turned on it will clean all database data and log current user out on app launch. Really convenient when debugging/developing stuff that needs fresh login each time.
To turn it on go to the "edit scheme menu" and turn it on:
> Clean boot option added

- AirCasting/CreateSessionViews/ChooseCustomLocationView.swift
- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/CreateSessionViews/ConfirmCreatingSessionView.swift
- AirCasting/CreateSessionViews/PlacePicker.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/Map/GoogleMapView.swift
https://trello.com/c/0TVcBz7m/538-custom-location-bug
> Resolved bug by pusing realtime update from PlacePicker.

- AirCasting/CoreData/PersistenceController+Database.swift
- AirCasting/SessionsSynchronization/Adapters/DataStore/SessionSynchronizationDatabase.swift
- AirCasting/SessionsSynchronization/Database/Database.swift
- AppDelegate+Injection.swift
This fixes this bug:
https://trello.com/c/kqXzDa8I
> Implement new version for saving session's urlLocation

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeViewModel.swift
- AirCasting/MainTabBarView.swift
Deleted BT Manager which was doing nothing there. Moved VM to it's view init. Structured code into easier redable parts.
> Refactor of ChooseSessionTypeView.

- AirCasting/CreateSessionViews/ChooseLocationPickerService.swift
- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeViewModel.swift
- AirCasting/SearchAndFollow/SearchLocation/SearchPickerService.swift
Few changes were requested in SearchView from the search and follow feature.
> Applied missing changes from the mother branch of that task - SearchView.

- AirCasting/AuthViews/CreateAccountView.swift
- AirCasting/Onboarding/AirBeamOnboarding.swift
- AirCasting/Onboarding/GetStarted.swift
- AirCasting/Onboarding/NearAirDescription.swift
- AirCasting/Onboarding/PrivacyOnboarding.swift
- AirCasting/Utils/Strings.swift
> Add check air near you to onboarding screens

- AirCasting/CreateSessionViews/SelectPeripheralView.swift
Improved the way the screen for selecting the device is scrolling. For now, the whole screen was able to scroll which could result in moving out of the screen the continue button when there were too many devices.
> Select device screen - scrolling improved

- AirCasting/SessionViews/StandaloneSessionCardView.swift
- AirCasting/Utils/Strings.swift
The text has been adjusted and centered. Space has been added before each card.
> Standalone - update card UI

- AirCasting/Dashboard/EmptyFixedDashboardView.swift
- AirCasting/Utils/Strings.swift
> Add new description text in empty dashboard for search and follow feature

- AirCasting/Map/GoogleMapView.swift
https://trello.com/c/VBSbsrKo/582-mobile-active-notes-flickering-current-location-dot-when-underneath-note
> Using zindex to place item higher.

- AirCasting/Onboarding/NearAirDescription.swift
https://trello.com/c/KL8w18pY/600-text-is-cut-off-screenshot
> Fit text into its boundries.

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
https://trello.com/c/7W2W4dKy/602-round-corners-of-buttons-screen
> Rounded corners on every button on the + screen.

- AirCasting/Map/style.json
change visibility of buildings on the map in the map style JSON file
> Adding building outlines to the maps

- AirCasting/CreateSessionViews/ChooseLocationPickerService.swift
- AirCasting/CreateSessionViews/PlacePicker/PlacePicker.swift
https://trello.com/c/vCC4TcfJ/636-show-the-full-adress-to-the-user-when-using-custom-location-on-fix-session
> Show full adress when using custom location on fixed session.

- AirCasting/ABConnector/BluetoothManager.swift
- AirCasting/ABConnector/SDCardAirBeamServices.swift
- AirCasting/SDSync/ViewsFlow/ClearingSDCard/ClearingSDCardViewModel.swift
- AirCasting/SessionViews/EditViewModel.swift
- AirCasting/Utils/InAppAlerts.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/FCbMnr5z/617-fix-dismiss-actions-for-alerts
> Fix alerts & timeout on BluetoothCommunicator

- AirCasting/SessionViews/ThresholdSettings/ThresholdsSettingsView.swift
https://trello.com/c/qEfi6Bub/640-heatmap-settings-layout
> Threshold settings buttons background

- AirCasting/AuthViews/CreateAccountView.swift
- AirCasting/AuthViews/SignInView.swift
- AirCasting/Models/AirBeamCellularSessionCreator.swift
- AirCasting/Models/AirBeamFixedWifiSessionCreator.swift
- AirCasting/Notes/NotesHandler.swift
- AirCasting/SessionViews/SessionCardView.swift
- AirCasting/SessionViews/SessionCartViewModel/DefaultDeleteSessionViewModel.swift
- AirCasting/SessionsSynchronization/Adapters/Services/SessionUploadService.swift
- AirCasting/Utils/Textfield.swift
https://trello.com/c/RKDIeMEn/639-missing-rounding
> Round missing corners - TextField + handled warnings

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/Dashboard/DashboardView.swift
- AirCasting/SearchAndFollow/SearchLocation/SearchView.swift
- AirCasting/SearchAndFollow/SearchLocation/SearchViewModel.swift
- AirCasting/SearchAndFollow/SearchMap/SearchMapView.swift
- AirCasting/SearchAndFollow/SearchMap/SearchMapViewModel.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/iCpkJZW0/643-add-finish-button-in-the-search-map-view
> Adding finish button to SearchMap

- AirCasting/SessionViews/ChartViewModel.swift
> Fix chart generating entries too early

- AirCasting/AuthViews/CreateAccountView.swift
https://trello.com/c/J31pMYJM/665-adding-loading-indicator-to-the-create-account-view
> Adding loading indicator to the create account view

- AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionCard.swift
- AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionHeader.swift
- AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionMapView.swift
https://trello.com/c/ZvbFcgXl/667-following-tap-parameter-card-should-expand-on-parameter-tap
> Handle card expand on tap

- AirCasting/SessionViews/ChartViewModel.swift
> Chart fix first hour average

- AirCasting/Onboarding/AirBeamOnboarding.swift
- AirCasting/Onboarding/NearAirDescription.swift
https://trello.com/c/HZsYWJ4x/673-hows-the-air-near-you-image-not-centered
> Images used on onboarding are now centered.

- AirCasting/SearchAndFollow/CompleteScreen/Views/SearchAndFollowChartView.swift
- AirCasting/SearchAndFollow/CompleteScreen/Views/SearchAndFollowChartViewModel.swift
- AirCasting/SessionViews/UIKitChartView.swift
https://trello.com/c/KQmMQHpj
It's a very basic version of the solution. We can work on it further later on.
> Add more space in the search and follow chart

- AirCasting/AuthViews/CreateAccountView.swift
- AirCasting/Utils/InAppAlerts.swift
https://trello.com/c/dj5ihID4/670-missing-alerts-for-the-create-account-view
> Fixing the problem with displaying alerts on create account view

- AirCasting/SearchAndFollow/CompleteScreen/Views/CompleteScreenViewModel.swift
https://trello.com/c/wLAlCFTU/685-sf-card-tapping-map-or-chart-twice-toggles-to-the-opposite-selection
> Fixing bug which allows the user toggling between map and chart 

- AirCasting/SearchAndFollow/AirBeamMeasurements/AirBeamStreamPrefix.swift
- AirCasting/SearchAndFollow/CompleteScreen/Views/CompleteScreenViewModel.swift
https://trello.com/c/pHXfgEao/688-sf-following-card-map-airbeam2-or-airbeam3-should-read-airbeam2-or-airbeam3
> Capitalized sensor name

- AirCasting/CoreData/Storages/MeasurementStreamStorage.swift
- AirCasting/Models/AirBeamCellularSessionCreator.swift
- AirCasting/Models/AirBeamFixedWifiSessionCreator.swift
> Give highest order to newly created fixed sessions

- AirCasting/Dashboard/DashboardView.swift
- AirCasting/MainTabBarView.swift
- AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionCard.swift
- AirCasting/SessionViews/SessionCardView.swift
https://trello.com/c/cqWBGFc9/672-icon-appears-on-map-graph-bug
> Fixing problem with appearing icons on the map and the graph

- AirCasting/SearchAndFollow/CompleteScreen/Services/SearchAndFollowCompleteScreenService.swift
- AirCasting/SearchAndFollow/CompleteScreen/Views/CompleteScreenViewModel.swift
https://trello.com/c/adGyvCUU/690-fast-unfollow-sf-crash
> Session is unfollowed without streams ready

- Readme.md
A small change in readme regarding the process of release update.
> Update release updating info

- AirCasting/Dashboard/DashboardView.swift
- AirCasting/Dashboard/Reordering/ReoredringSessionCard.swift
- AirCasting/SearchAndFollow/SearchMap/BottomCard.swift
- AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionCard.swift
- AirCasting/SessionViews/SessionCardView.swift
- AirCasting/SessionViews/StandaloneSessionCardView.swift
- Modules/AirCastingStyling/Sources/AirCastingStyling/CardShadow.swift
- Modules/AirCastingStyling/Sources/AirCastingStyling/Color.swift
https://trello.com/c/DWKJchFj/370-dashboard-cards-make-them-look-like-android
> Changing shadow on the cards

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/CoreData/AirCasting.xcdatamodeld/.xccurrentversion
- AirCasting/CoreData/AirCasting.xcdatamodeld/AirCasting v7.xcdatamodel/contents
- AirCasting/CoreData/PersistenceController+Database.swift
- AirCasting/CoreData/Storages/MeasurementStreamStorage.swift
- AirCasting/Info.plist
- AirCasting/Map/GoogleMapView.swift
- AirCasting/Notes/AddNote/AddNoteView.swift
- AirCasting/Notes/AddNote/AddNoteViewModel.swift
- AirCasting/Notes/EditNote/EditNoteView.swift
- AirCasting/Notes/EditNote/EditNoteViewModel.swift
- AirCasting/Notes/Note.swift
- AirCasting/Notes/NotesHandler.swift
- AirCasting/SessionsSynchronization/Adapters/DataStore/SessionSynchronizationDatabase.swift
- AirCasting/SessionsSynchronization/Adapters/Services/SessionUploadService.swift
- AirCasting/SessionsSynchronization/Controller/Interfaces/SessionSynchronizationStore.swift
- AirCasting/SessionsSynchronization/Controller/Interfaces/SessionUpstream.swift
- AirCasting/SessionsSynchronization/Controller/SessionSynchronizationController.swift
- AirCasting/SessionsSynchronization/Controller/Utils/SessionsSynchronizationStoreDataConverter.swift
- AirCasting/SessionsSynchronization/Database/Database.swift
- AirCasting/SessionsSynchronization/Database/DatabaseNote.swift
- AirCasting/Utils/DownloadableImage.swift
- AirCasting/Utils/PhotoPicker.swift
- AirCasting/Utils/Strings.swift
> Attach photo to a note

- AirCasting/Onboarding/GetStarted.swift
https://trello.com/c/h14CRxDd/710-fixing-get-started-button-in-first-onboarding-screen
If anyone will test, please check if the layout is the same. For me looks identically.
> GetStarted button on first OnBoarding screen

- AirCasting/SearchAndFollow/SearchMap/SearchMapViewModel.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/wb42o0rv/712-remove-dots-loading-session
> Clearing session list on redo button tap.

- AirCasting/CreateSessionViews/SelectDeviceView.swift
https://trello.com/c/97cN2ttT/716-selectdevice-view-adding-indicator-to-the-buttons
> SelectDevice View UI changes

- AirCasting/SearchAndFollow/SearchMap/SearchMapView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/6aGJVrqa/717-info-when-no-session-in-sf
The goal here: show text which alerts user that there are no sessions in this area. This text should be shown on white gradient.
> Show info when no session in area

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/CreateSessionViews/MoreInfoPopupView.swift
- AirCasting/ForgotPassword/Views/ForgotPasswordView.swift
- AirCasting/Notes/AddNote/AddNoteView.swift
- AirCasting/Notes/EditNote/EditNoteView.swift
- AirCasting/SessionViews/DeleteView.swift
- AirCasting/SessionViews/EditView.swift
- AirCasting/SessionViews/ShareSession/ShareLocationlessSessionView.swift
- AirCasting/SessionViews/ShareSession/ShareSessionView.swift
- AirCasting/Settings/BackendSettingsView.swift
- AirCasting/Utils/XMarkButton.swift
- AirCasting/Utils/XmarkButton.swift
If I omitted any modal sheet please let me know. In the ticket, you can find places where I added close buttons.
https://trello.com/c/wDOaEuyL/719-adding-close-button-to-modalsheets-in-the-app
> Adding close buttons to modal sheets

- AirCasting/AuthViews/AuthErorrHandling.swift
- AirCasting/AuthViews/CreateAccountView.swift
- AirCasting/AuthViews/SignInView.swift
- AirCasting/Utils/Textfield.swift
https://trello.com/c/oTc4KUgl/714-ui-changes-in-signin-and-createaccount-views
I have no idea how to name that property `checkingIf: Bool = false` if you will have better ideas let me know 😃
> CreateAccount and SingIn views changes

- AirCasting/SessionViews/EditView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/vFLVu4mA/713-adding-labels-to-editsessionview
> Adding info labels to EditSessionView

- AirCasting/Onboarding/AirBeamOnboarding.swift
- AirCasting/Onboarding/GetStarted.swift
- AirCasting/Onboarding/NearAirDescription.swift
- AirCasting/Onboarding/PrivacyOnboarding.swift
https://trello.com/c/nSyUxjxm/727-onboarding-ui-changes
> Onboarding UI changes

- AirCasting/CoreData/Storages/ExternalSessionsStore.swift
- AirCasting/SearchAndFollow/AirBeamMeasurements/AirBeamMeasurementsDownloader.swift
- AirCasting/SearchAndFollow/CompleteScreen/Models/ExternalSessionWithStreamsAndMeasurements.swift
- AirCasting/SearchAndFollow/CompleteScreen/Services/SearchAndFollowCompleteScreenService.swift
- AirCasting/SearchAndFollow/CompleteScreen/Views/CompleteScreenViewModel.swift
- AirCasting/SearchAndFollow/CompleteScreen/Views/StaticSingleStreamView.swift
https://trello.com/c/rRDkyojc/702-changes-apply
**The goal:** To cover every comment Ania mentioned in the ticket, nothing more.
**Done:**
1. Function for downloading streams error handling changed
2. Naming
3. Log description improvements
4. Show `-` when there is no measurements
5. Deleted sensorPackageName as it was the same as streamName
> S&F logic small refactor + UI improved

- AirCasting/Dashboard/AirSectionPickerView.swift
https://trello.com/c/m5Yadk8W/730-dashboard-increase-the-vertical-spacing-for-section-picker
> Increasing the vertical spacing for Section Picker

- AirCasting/AuthViews/UserSettings.swift
- AirCasting/Map/CreatingSessionMapView.swift
- AirCasting/Map/GoogleMapView.swift
- AirCasting/SearchAndFollow/CompleteScreen/Views/SearchCompleteScreenMapView.swift
- AirCasting/SearchAndFollow/SearchAndFollowMap/SearchAndFollowMap.swift
- AirCasting/SearchAndFollow/SearchMap/SearchMapView.swift
- AirCasting/Settings/SettingsView.swift
- AirCasting/Utils/Constants.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/lpcbOLmJ/725-settings-sattelite-view-option
> Satellite map - Settings

- AirCasting/SDSync/ViewsFlow/BackendSyncCompleted/BackendSyncCompletedView.swift
- AirCasting/SDSync/ViewsFlow/SDRestartAB/SDRestartABView.swift
- AirCasting/SDSync/ViewsFlow/SDSyncComplete/SDSyncCompleteView.swift
- AirCasting/SDSync/ViewsFlow/SDSyncUnplugAB/UnplugABView.swift
https://trello.com/c/n8RqGgos/735-sd-sync-text-cut-off
> Fixing cut off text on UnplugAB View

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/Onboarding/GetStarted.swift
- AirCasting/RootAppView.swift
- AirCasting/Settings/SettingsView.swift
https://trello.com/c/DqCOXCSC/322-optimize-app-for-ipads
> Navigation views to stack navigation - iPad UI adjust.

- AirCasting/Extensions/SensorThreshold.swift
https://trello.com/c/KBcFIxT9/757-hlu-threshold-values-should-be-included-in-the-color-for-which-they-define-the-max-value
> Upper bound is included in the threshold color.

- AirCasting/Graph/AirCastingGraphSimplifier.swift
- AirCasting/Graph/External/ExternalGraph.swift
- AirCasting/Graph/Graph.swift
- AirCasting/Graph/StatisticsContainer/Adapters/StandardStatisticsCalculator.swift
- AirCasting/Map/AirMapView.swift
- AirCasting/SearchAndFollow/CompleteScreen/Views/SearchAndFollowChartView.swift
- AirCasting/SearchAndFollow/CompleteScreen/Views/StaticSingleStreamView.swift
- AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionMapView.swift
- AirCasting/SessionViews/SingleMeasurementView.swift
https://trello.com/c/AALN7YhI/731-implement-proper-mathematical-rounding-for-avg-values
> Proper mathematical rounding - measurements.

- AirCasting/SearchAndFollow/SearchMap/SearchMapView.swift
https://trello.com/c/F36PtkM9/759-181-7-sf-map-tapping-finish-navigates-to-the-last-tab-user-was-on-should-always-navigate-to-the-following-tab
> On finish button tap - direct user to following section.

- AirCasting/AuthViews/CreateAccountView.swift
- AirCasting/AuthViews/SignInView.swift
- AirCasting/Utils/InAppAlerts.swift
- AirCasting/Utils/Strings.swift
> Add no connection alert to sign in and sign up views

- AirCasting/Assets.xcassets/Bitmap.imageset/Contents.json
- AirCasting/Onboarding/GetStarted.swift
https://trello.com/c/DRsxTWfP/764-ipad-landscape-intro-wizard-first-screen-cut-off-cant-continue
🚩This is the temporary, not ideal fix. As soon as Gosia will be back, I will reach out to her to get images designed specifically for iPad.
> Make image smaller so that user can access GetStarted button.

- AirCasting/APICommunicator/ShareSessionAPI.swift
> Fix request for exporting session file

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/APICommunicator/ShareSessionAPI.swift
- AirCastingTests/API/ShareSessionFileTest.swift
This is a simple test for checking if we are sending a right request for sharing session via email
> Add test for sending request to share session

- AirCasting/SessionViews/ExternalSessionsViews/ExternalSessionHeader.swift
- AirCasting/SessionViews/SessionHeaderView.swift
https://trello.com/c/0DWSETlo/761-externalsessioncard-chevron-doesnt-work-properly
> Moved chevron image logic to computed property.

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/APICommunicator/DormantStreamAlertAPI.swift
- AirCasting/AuthViews/UserSettings.swift
- AirCasting/SearchAndFollow/MapSessionsDownloader/API/SessionsForLocationDownloader.swift
- AirCasting/Settings/SettingsController.swift
- AirCasting/Settings/SettingsView.swift
- AirCasting/Settings/SettingsViewModel.swift
- AirCasting/Utils/Constants.swift
- AirCasting/Utils/InAppAlerts.swift
- AirCasting/Utils/Strings.swift
- AirCastingTests/API/DormantStreamAlertAPITest.swift
- AppDelegate+Injection.swift
> Dormant sessions alert

- AirCasting/FeatureFlags/FeatureFlagProviders/DefaultFeatureFlagProvider.swift
https://trello.com/c/kuNnq5DC/774-cleanup-feature-flags
> Feature flags default value changes to always true.

- AirCasting/SessionViews/ThresholdAlerts/ThresholdAlertSheetViewModel.swift
- AirCasting/SessionViews/ThresholdAlerts/ThresholdAlertsController.swift
Turns out we need to sent a full sensor name for the alerts to work
> Create alert with full sensor name

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/SearchAndFollow/SearchLocation/SearchViewModel.swift
- AirCastingTests/SearchAndFollowTests/AirBeamMeasurementDownloaderTests.swift
- AirCastingTests/SearchAndFollowTests/MapDownloaderMeasurementTypeTests.swift
- AirCastingTests/SearchAndFollowTests/MapDownloaderSensorTypeTests.swift
- AirCastingTests/SearchAndFollowTests/MapDownloaderUnitSymbolTests.swift
- AirCastingTests/SearchAndFollowTests/SearchViewModelTests.swift
- AirCastingTests/SearchAndFollowTests/SessionForLocationDownloaderTests.swift
- AirCastingTests/Utils/TestDefaultProviding.swift
https://trello.com/c/lAnLeTxO/666-write-tests-for-search-and-follow-feature
> Search and follow - UnitTests

- AirCasting/MobilePeripheralSessionManager.swift
Ensures that every measurement bunch gets the same location. This was a missing part after applying the same time for every bunch.
https://trello.com/c/Y4OVpvQH/347-improve-2hr-9hr-averaging-function-so-all-the-averages-are-precisely-5-sec-1-min
> The same location for every 5 measurements.

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/AuthViews/UserAuthenticationSession.swift
- AirCasting/Bootstrap/AppBootstrap.swift
- AirCasting/Utils/Assertions.swift
- AirCasting/Utils/Logging/CrashlyticsErrorLogger.swift
- AirCasting/Utils/Logging/CrashlyticsLogger.swift
- AirCasting/Utils/Logging/FileLogger/FileLogger.swift
- AirCasting/Utils/Logging/Helpers/CompositeLogger.swift
- AirCasting/Utils/Logging/Helpers/ScheduledLogger.swift
- AirCasting/Utils/Logging/Helpers/ThresholdLoggerProxy.swift
- AirCasting/Utils/Logging/LoggerBuilder.swift
- AirCasting/Utils/Publishers/LogErrorAndCompletePublisher.swift
- AirCasting/Utils/Publishers/LogErrorPublisher.swift
- AirCasting/Utils/Publishers/LogEvent.swift
- AppDelegate+Injection.swift
* Build type (`BETA|RELEASE`) added to crashlytics
* Crashlytics error logger split from general logger
* User ID added to crashlytics errors
* Fixed error file paths
> Logging enhancements

- AirCasting.xcodeproj/project.pbxproj
- AirCasting/Dashboard/Reordering/CustomSwipeAction.swift
- AirCasting/Dashboard/Reordering/ReorderingDashboard.swift
- AirCasting/Dashboard/Reordering/ReorderingDashboardViewModel.swift
- AirCasting/Dashboard/Reordering/ReorderingSessionHeader.swift
- AirCasting/Dashboard/Reordering/ReoredringSessionCard.swift
- AirCasting/MainTabBarView.swift
- AirCasting/Models/Session+Mock.swift
- AirCasting/SessionViews/SingleMeasurementView.swift
The user has the possibility to unfollow a fixed session by swiping it to the left during reordering
https://trello.com/c/cOvvI3rG
> Clearing sessions during reorder

- AirCasting/Dashboard/DashboardView.swift
https://trello.com/c/Z3CVr3Pg/794-11102-following-rearrange-and-search-icons-are-missing
> Icon for rearrange dissapears.

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
> New choose session view layout (iPhone SE fix)

- AirCasting/APICommunicator/CreateThresholdAlertService.swift
https://trello.com/c/WByJ1gCG
Backend need timezone_offset to calculate whether the mail should be sent or not.
> Add timezone offset to request when creating threshold alert

- AirCasting/ABConnector/SDSyncController.swift
- AirCasting/SDSync/MobileSessions/SDCardMobileSessionsSavingService.swift
- AirCasting/SDSync/MobileSessions/SDSyncAveragingService.swift
- AirCasting/SDSync/ViewsFlow/SDSyncingAB/SDSyncViewModel.swift
Remove logs and move to Finalizing screen sooner
> Sd sync polishing

- AirCasting/AuthViews/LogoutController.swift
- AirCasting/Utils/Bluetooth/NewBluetoothManager.swift
> Finish sampling on logout

- AirCasting/Settings/SettingsView.swift
- AirCasting/Settings/ShareLogsViewModel.swift
- AirCasting/Utils/Logging/CrashlyticsErrorLogger.swift
- AirCasting/Utils/Logging/CrashlyticsLogger.swift
- AirCasting/Utils/Logging/FileLogger/DocumentsFileLoggerStore.swift
- AirCasting/Utils/Logging/FileLogger/FileLogger.swift
- AirCasting/Utils/Logging/FileLogger/FileLoggerDisposer.swift
- AirCasting/Utils/Logging/Log.swift
- AirCasting/Utils/Logging/LoggerBuilder.swift
- AppDelegate+Injection.swift
Taken from GoogleMaps refractor.
Thanks Paweł!
> Logger deadlock fixed

- AirCasting/CoreData/NSManagedObjectContext+Utils.swift
- AirCasting/Services/DownloadMeasurmentsService.swift
Remove unnecessary context save when removing old measurements.
> Context save changes in DownloadMeasurementService

- AirCasting/SDSync/MobileSessions/SDSyncMobileSessionStorage.swift
https://trello.com/c/QtmaH0UQ/884-mobile-dormant-update-session-title-text
> Imported sessions from SD - title update

- AirCasting/Utils/Strings.swift
https://trello.com/c/weDloQai/883-mobile-active-did-you-know-update-text
> Mobile active hint - text update

- AirCasting/SessionViews/UIKitChartView.swift
https://trello.com/c/pvoVBt4y/876-following-mobile-active-dont-display-cross-hairs-on-chart-tap
> Disabled the ability to highlight a point on chart

- AirCasting/Graph/Graph.swift
https://trello.com/c/5XiL8wQO/873-following-graph-update-graph-in-real-time
Currently, after 24 hours of collecting measurements, we always have the same number of total measurements. The reason for this is that when we collect new measurements, we always delete the last ones. This makes the total count always the same. To continue preventing all the time graph updates, we are introducing date checking of the lastest measurement.
The next thing was about time correctness on the graph and the session itself. There was some discrepancy, becouse of our averaging service and the fact that the time is taken from x point of the latest point (which was previously averaged). To prevent such a scenario we are increasing the threshold to 1500, as the max value for measurements should not exceed …
> Condition for graph update and averaging threshold changed

- AirCasting/SearchAndFollow/SearchLocation/SearchView.swift
- AirCasting/SearchAndFollow/SearchLocation/SearchViewModel.swift
https://trello.com/c/WqkeHh2x/881-follow-session-hide-everything-below-the-session-location-field-default-selections-are-particulate-matter-airbeam
> Follow session - disable ability to change parameter

- AirCasting/CreateSessionViews/ChooseSessionType/ChooseSessionTypeView.swift
- AirCasting/Utils/Strings.swift
https://trello.com/c/qLcbhKav/882-lets-begin-update-text
> Lets begin - buttons text aligned, text updated.
